/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.twitter.category

import com.vanniktech.emoji.twitter.TwitterEmoji

internal object ObjectsCategoryChunk1 {
  internal val EMOJIS: List<TwitterEmoji> = listOf(
    TwitterEmoji("\ud83c\udfac", listOf("clapper"), 7, 43),
    TwitterEmoji("\ud83d\udcfa", listOf("tv"), 29, 50),
    TwitterEmoji("\ud83d\udcf7", listOf("camera"), 29, 47),
    TwitterEmoji("\ud83d\udcf8", listOf("camera_with_flash"), 29, 48),
    TwitterEmoji("\ud83d\udcf9", listOf("video_camera"), 29, 49),
    TwitterEmoji("\ud83d\udcfc", listOf("vhs"), 29, 52),
    TwitterEmoji("\ud83d\udd0d", listOf("mag"), 30, 6),
    TwitterEmoji("\ud83d\udd0e", listOf("mag_right"), 30, 7),
    TwitterEmoji("\ud83d\udd6f\ufe0f", listOf("candle"), 31, 23),
    TwitterEmoji("\ud83d\udca1", listOf("bulb"), 28, 18),
    TwitterEmoji("\ud83d\udd26", listOf("flashlight"), 30, 31),
    TwitterEmoji("\ud83c\udfee", listOf("izakaya_lantern", "lantern"), 10, 36),
    TwitterEmoji("\ud83e\ude94", listOf("diya_lamp"), 55, 17),
    TwitterEmoji("\ud83d\udcd4", listOf("notebook_with_decorative_cover"), 29, 12),
    TwitterEmoji("\ud83d\udcd5", listOf("closed_book"), 29, 13),
    TwitterEmoji("\ud83d\udcd6", listOf("book", "open_book"), 29, 14),
    TwitterEmoji("\ud83d\udcd7", listOf("green_book"), 29, 15),
    TwitterEmoji("\ud83d\udcd8", listOf("blue_book"), 29, 16),
    TwitterEmoji("\ud83d\udcd9", listOf("orange_book"), 29, 17),
    TwitterEmoji("\ud83d\udcda", listOf("books"), 29, 18),
    TwitterEmoji("\ud83d\udcd3", listOf("notebook"), 29, 11),
    TwitterEmoji("\ud83d\udcd2", listOf("ledger"), 29, 10),
    TwitterEmoji("\ud83d\udcc3", listOf("page_with_curl"), 28, 57),
    TwitterEmoji("\ud83d\udcdc", listOf("scroll"), 29, 20),
    TwitterEmoji("\ud83d\udcc4", listOf("page_facing_up"), 28, 58),
    TwitterEmoji("\ud83d\udcf0", listOf("newspaper"), 29, 40),
    TwitterEmoji("\ud83d\uddde\ufe0f", listOf("rolled_up_newspaper"), 32, 35),
    TwitterEmoji("\ud83d\udcd1", listOf("bookmark_tabs"), 29, 9),
    TwitterEmoji("\ud83d\udd16", listOf("bookmark"), 30, 15),
    TwitterEmoji("\ud83c\udff7\ufe0f", listOf("label"), 10, 48),
    TwitterEmoji("\ud83d\udcb0", listOf("moneybag"), 28, 38),
    TwitterEmoji("\ud83e\ude99", listOf("coin"), 55, 22),
    TwitterEmoji("\ud83d\udcb4", listOf("yen"), 28, 42),
    TwitterEmoji("\ud83d\udcb5", listOf("dollar"), 28, 43),
    TwitterEmoji("\ud83d\udcb6", listOf("euro"), 28, 44),
    TwitterEmoji("\ud83d\udcb7", listOf("pound"), 28, 45),
    TwitterEmoji("\ud83d\udcb8", listOf("money_with_wings"), 28, 46),
    TwitterEmoji("\ud83d\udcb3", listOf("credit_card"), 28, 41),
    TwitterEmoji("\ud83e\uddfe", listOf("receipt"), 54, 49),
    TwitterEmoji("\ud83d\udcb9", listOf("chart"), 28, 47),
    TwitterEmoji("\u2709\ufe0f", listOf("email", "envelope"), 60, 1),
    TwitterEmoji("\ud83d\udce7", listOf("e-mail"), 29, 31),
    TwitterEmoji("\ud83d\udce8", listOf("incoming_envelope"), 29, 32),
    TwitterEmoji("\ud83d\udce9", listOf("envelope_with_arrow"), 29, 33),
    TwitterEmoji("\ud83d\udce4", listOf("outbox_tray"), 29, 28),
    TwitterEmoji("\ud83d\udce5", listOf("inbox_tray"), 29, 29),
    TwitterEmoji("\ud83d\udce6", listOf("package"), 29, 30),
    TwitterEmoji("\ud83d\udceb", listOf("mailbox"), 29, 35),
    TwitterEmoji("\ud83d\udcea", listOf("mailbox_closed"), 29, 34),
    TwitterEmoji("\ud83d\udcec", listOf("mailbox_with_mail"), 29, 36),
    TwitterEmoji("\ud83d\udced", listOf("mailbox_with_no_mail"), 29, 37),
    TwitterEmoji("\ud83d\udcee", listOf("postbox"), 29, 38),
    TwitterEmoji("\ud83d\uddf3\ufe0f", listOf("ballot_box_with_ballot"), 32, 40),
    TwitterEmoji("\u270f\ufe0f", listOf("pencil2"), 60, 26),
    TwitterEmoji("\u2712\ufe0f", listOf("black_nib"), 60, 27),
    TwitterEmoji("\ud83d\udd8b\ufe0f", listOf("lower_left_fountain_pen"), 32, 0),
    TwitterEmoji("\ud83d\udd8a\ufe0f", listOf("lower_left_ballpoint_pen"), 31, 61),
    TwitterEmoji("\ud83d\udd8c\ufe0f", listOf("lower_left_paintbrush"), 32, 1),
    TwitterEmoji("\ud83d\udd8d\ufe0f", listOf("lower_left_crayon"), 32, 2),
    TwitterEmoji("\ud83d\udcdd", listOf("memo", "pencil"), 29, 21),
    TwitterEmoji("\ud83d\udcbc", listOf("briefcase"), 28, 50),
    TwitterEmoji("\ud83d\udcc1", listOf("file_folder"), 28, 55),
    TwitterEmoji("\ud83d\udcc2", listOf("open_file_folder"), 28, 56),
    TwitterEmoji("\ud83d\uddc2\ufe0f", listOf("card_index_dividers"), 32, 27),
    TwitterEmoji("\ud83d\udcc5", listOf("date"), 28, 59),
    TwitterEmoji("\ud83d\udcc6", listOf("calendar"), 28, 60),
    TwitterEmoji("\ud83d\uddd2\ufe0f", listOf("spiral_note_pad"), 32, 31),
    TwitterEmoji("\ud83d\uddd3\ufe0f", listOf("spiral_calendar_pad"), 32, 32),
    TwitterEmoji("\ud83d\udcc7", listOf("card_index"), 28, 61),
    TwitterEmoji("\ud83d\udcc8", listOf("chart_with_upwards_trend"), 29, 0),
    TwitterEmoji("\ud83d\udcc9", listOf("chart_with_downwards_trend"), 29, 1),
    TwitterEmoji("\ud83d\udcca", listOf("bar_chart"), 29, 2),
    TwitterEmoji("\ud83d\udccb", listOf("clipboard"), 29, 3),
    TwitterEmoji("\ud83d\udccc", listOf("pushpin"), 29, 4),
    TwitterEmoji("\ud83d\udccd", listOf("round_pushpin"), 29, 5),
    TwitterEmoji("\ud83d\udcce", listOf("paperclip"), 29, 6),
    TwitterEmoji("\ud83d\udd87\ufe0f", listOf("linked_paperclips"), 31, 60),
    TwitterEmoji("\ud83d\udccf", listOf("straight_ruler"), 29, 7),
    TwitterEmoji("\ud83d\udcd0", listOf("triangular_ruler"), 29, 8),
    TwitterEmoji("\u2702\ufe0f", listOf("scissors"), 59, 60),
    TwitterEmoji("\ud83d\uddc3\ufe0f", listOf("card_file_box"), 32, 28),
    TwitterEmoji("\ud83d\uddc4\ufe0f", listOf("file_cabinet"), 32, 29),
    TwitterEmoji("\ud83d\uddd1\ufe0f", listOf("wastebasket"), 32, 30),
    TwitterEmoji("\ud83d\udd12", listOf("lock"), 30, 11),
    TwitterEmoji("\ud83d\udd13", listOf("unlock"), 30, 12),
    TwitterEmoji("\ud83d\udd0f", listOf("lock_with_ink_pen"), 30, 8),
    TwitterEmoji("\ud83d\udd10", listOf("closed_lock_with_key"), 30, 9),
    TwitterEmoji("\ud83d\udd11", listOf("key"), 30, 10),
    TwitterEmoji("\ud83d\udddd\ufe0f", listOf("old_key"), 32, 34),
    TwitterEmoji("\ud83d\udd28", listOf("hammer"), 30, 33),
    TwitterEmoji("\ud83e\ude93", listOf("axe"), 55, 16),
    TwitterEmoji("\u26cf\ufe0f", listOf("pick"), 59, 25),
    TwitterEmoji("\u2692\ufe0f", listOf("hammer_and_pick"), 59, 3),
    TwitterEmoji("\ud83d\udee0\ufe0f", listOf("hammer_and_wrench"), 38, 53),
    TwitterEmoji("\ud83d\udde1\ufe0f", listOf("dagger_knife"), 32, 36),
    TwitterEmoji("\u2694\ufe0f", listOf("crossed_swords"), 59, 5),
    TwitterEmoji("\ud83d\udca3", listOf("bomb"), 28, 20),
    TwitterEmoji("\ud83e\ude83", listOf("boomerang"), 55, 5),
    TwitterEmoji("\ud83c\udff9", listOf("bow_and_arrow"), 10, 50),
    TwitterEmoji("\ud83d\udee1\ufe0f", listOf("shield"), 38, 54),
  )
}
