/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.twitter.category

import com.vanniktech.emoji.twitter.TwitterEmoji

internal object SmileysAndPeopleCategoryChunk1 {
  internal val EMOJIS: List<TwitterEmoji> = listOf(
    TwitterEmoji("\ud83d\ude2b", listOf("tired_face"), 33, 28),
    TwitterEmoji("\ud83e\udd71", listOf("yawning_face"), 44, 34),
    TwitterEmoji("\ud83d\ude24", listOf("triumph"), 33, 21),
    TwitterEmoji("\ud83d\ude21", listOf("rage"), 33, 18),
    TwitterEmoji("\ud83d\ude20", listOf("angry"), 33, 17),
    TwitterEmoji("\ud83e\udd2c", listOf("face_with_symbols_on_mouth", "serious_face_with_symbols_covering_mouth"), 41, 19),
    TwitterEmoji("\ud83d\ude08", listOf("smiling_imp"), 32, 55),
    TwitterEmoji("\ud83d\udc7f", listOf("imp"), 25, 42),
    TwitterEmoji("\ud83d\udc80", listOf("skull"), 25, 43),
    TwitterEmoji(
      unicode = "\u2620",
      shortcodes = listOf("skull_and_crossbones"),
      x = 58,
      y = 32,
      variants = listOf(
        TwitterEmoji("\u2620\ufe0f", emptyList(), 58, 32),
      ),
    ),
    TwitterEmoji("\ud83d\udca9", listOf("hankey", "poop", "shit"), 28, 26),
    TwitterEmoji("\ud83e\udd21", listOf("clown_face"), 40, 53),
    TwitterEmoji("\ud83d\udc79", listOf("japanese_ogre"), 25, 31),
    TwitterEmoji("\ud83d\udc7a", listOf("japanese_goblin"), 25, 32),
    TwitterEmoji("\ud83d\udc7b", listOf("ghost"), 25, 33),
    TwitterEmoji("\ud83d\udc7d", listOf("alien"), 25, 40),
    TwitterEmoji("\ud83d\udc7e", listOf("space_invader"), 25, 41),
    TwitterEmoji("\ud83e\udd16", listOf("robot_face"), 39, 44),
    TwitterEmoji("\ud83d\ude3a", listOf("smiley_cat"), 33, 46),
    TwitterEmoji("\ud83d\ude38", listOf("smile_cat"), 33, 44),
    TwitterEmoji("\ud83d\ude39", listOf("joy_cat"), 33, 45),
    TwitterEmoji("\ud83d\ude3b", listOf("heart_eyes_cat"), 33, 47),
    TwitterEmoji("\ud83d\ude3c", listOf("smirk_cat"), 33, 48),
    TwitterEmoji("\ud83d\ude3d", listOf("kissing_cat"), 33, 49),
    TwitterEmoji("\ud83d\ude40", listOf("scream_cat"), 33, 52),
    TwitterEmoji("\ud83d\ude3f", listOf("crying_cat_face"), 33, 51),
    TwitterEmoji("\ud83d\ude3e", listOf("pouting_cat"), 33, 50),
    TwitterEmoji("\ud83d\ude48", listOf("see_no_evil"), 34, 51),
    TwitterEmoji("\ud83d\ude49", listOf("hear_no_evil"), 34, 52),
    TwitterEmoji("\ud83d\ude4a", listOf("speak_no_evil"), 34, 53),
    TwitterEmoji("\ud83d\udc8c", listOf("love_letter"), 27, 9),
    TwitterEmoji("\ud83d\udc98", listOf("cupid"), 28, 9),
    TwitterEmoji("\ud83d\udc9d", listOf("gift_heart"), 28, 14),
    TwitterEmoji("\ud83d\udc96", listOf("sparkling_heart"), 28, 7),
    TwitterEmoji("\ud83d\udc97", listOf("heartpulse"), 28, 8),
    TwitterEmoji("\ud83d\udc93", listOf("heartbeat"), 28, 4),
    TwitterEmoji("\ud83d\udc9e", listOf("revolving_hearts"), 28, 15),
    TwitterEmoji("\ud83d\udc95", listOf("two_hearts"), 28, 6),
    TwitterEmoji("\ud83d\udc9f", listOf("heart_decoration"), 28, 16),
    TwitterEmoji(
      unicode = "\u2763",
      shortcodes = listOf("heavy_heart_exclamation_mark_ornament"),
      x = 60,
      y = 43,
      variants = listOf(
        TwitterEmoji("\u2763\ufe0f", emptyList(), 60, 43),
      ),
    ),
    TwitterEmoji("\ud83d\udc94", listOf("broken_heart"), 28, 5),
    TwitterEmoji(
      unicode = "\u2764\u200d\ud83d\udd25",
      shortcodes = listOf("heart_on_fire"),
      x = 60,
      y = 44,
      variants = listOf(
        TwitterEmoji("\u2764\ufe0f\u200d\ud83d\udd25", emptyList(), 60, 44),
      ),
    ),
    TwitterEmoji(
      unicode = "\u2764\u200d\ud83e\ude79",
      shortcodes = listOf("mending_heart"),
      x = 60,
      y = 45,
      variants = listOf(
        TwitterEmoji("\u2764\ufe0f\u200d\ud83e\ude79", emptyList(), 60, 45),
      ),
    ),
    TwitterEmoji(
      unicode = "\u2764",
      shortcodes = listOf("heart"),
      x = 60,
      y = 46,
      variants = listOf(
        TwitterEmoji("\u2764\ufe0f", emptyList(), 60, 46),
      ),
    ),
    TwitterEmoji("\ud83e\ude77", listOf("pink_heart"), 54, 58),
    TwitterEmoji("\ud83e\udde1", listOf("orange_heart"), 54, 20),
    TwitterEmoji("\ud83d\udc9b", listOf("yellow_heart"), 28, 12),
    TwitterEmoji("\ud83d\udc9a", listOf("green_heart"), 28, 11),
    TwitterEmoji("\ud83d\udc99", listOf("blue_heart"), 28, 10),
    TwitterEmoji("\ud83e\ude75", listOf("light_blue_heart"), 54, 56),
    TwitterEmoji("\ud83d\udc9c", listOf("purple_heart"), 28, 13),
    TwitterEmoji("\ud83e\udd0e", listOf("brown_heart"), 39, 31),
    TwitterEmoji("\ud83d\udda4", listOf("black_heart"), 32, 21),
    TwitterEmoji("\ud83e\ude76", listOf("grey_heart"), 54, 57),
    TwitterEmoji("\ud83e\udd0d", listOf("white_heart"), 39, 30),
    TwitterEmoji("\ud83d\udc8b", listOf("kiss"), 27, 8),
    TwitterEmoji("\ud83d\udcaf", listOf("100"), 28, 37),
    TwitterEmoji("\ud83d\udca2", listOf("anger"), 28, 19),
    TwitterEmoji("\ud83d\udca5", listOf("boom", "collision"), 28, 22),
    TwitterEmoji("\ud83d\udcab", listOf("dizzy"), 28, 33),
    TwitterEmoji("\ud83d\udca6", listOf("sweat_drops"), 28, 23),
    TwitterEmoji("\ud83d\udca8", listOf("dash"), 28, 25),
    TwitterEmoji(
      unicode = "\ud83d\udd73",
      shortcodes = listOf("hole"),
      x = 31,
      y = 25,
      variants = listOf(
        TwitterEmoji("\ud83d\udd73\ufe0f", emptyList(), 31, 25),
      ),
    ),
    TwitterEmoji("\ud83d\udcac", listOf("speech_balloon"), 28, 34),
    TwitterEmoji(
      unicode = "\ud83d\udc41\u200d\ud83d\udde8",
      shortcodes = listOf("eye-in-speech-bubble"),
      x = 12,
      y = 3,
      variants = listOf(
        TwitterEmoji("\ud83d\udc41\ufe0f\u200d\ud83d\udde8\ufe0f", emptyList(), 12, 3),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udde8",
      shortcodes = listOf("left_speech_bubble"),
      x = 32,
      y = 38,
      variants = listOf(
        TwitterEmoji("\ud83d\udde8\ufe0f", emptyList(), 32, 38),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\uddef",
      shortcodes = listOf("right_anger_bubble"),
      x = 32,
      y = 39,
      variants = listOf(
        TwitterEmoji("\ud83d\uddef\ufe0f", emptyList(), 32, 39),
      ),
    ),
    TwitterEmoji("\ud83d\udcad", listOf("thought_balloon"), 28, 35),
    TwitterEmoji("\ud83d\udca4", listOf("zzz"), 28, 21),
    TwitterEmoji(
      unicode = "\ud83d\udc4b",
      shortcodes = listOf("wave"),
      x = 12,
      y = 49,
      variants = listOf(
        TwitterEmoji("\ud83d\udc4b\ud83c\udffb", emptyList(), 12, 50),
        TwitterEmoji("\ud83d\udc4b\ud83c\udffc", emptyList(), 12, 51),
        TwitterEmoji("\ud83d\udc4b\ud83c\udffd", emptyList(), 12, 52),
        TwitterEmoji("\ud83d\udc4b\ud83c\udffe", emptyList(), 12, 53),
        TwitterEmoji("\ud83d\udc4b\ud83c\udfff", emptyList(), 12, 54),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd1a",
      shortcodes = listOf("raised_back_of_hand"),
      x = 39,
      y = 58,
      variants = listOf(
        TwitterEmoji("\ud83e\udd1a\ud83c\udffb", emptyList(), 39, 59),
        TwitterEmoji("\ud83e\udd1a\ud83c\udffc", emptyList(), 39, 60),
        TwitterEmoji("\ud83e\udd1a\ud83c\udffd", emptyList(), 39, 61),
        TwitterEmoji("\ud83e\udd1a\ud83c\udffe", emptyList(), 40, 0),
        TwitterEmoji("\ud83e\udd1a\ud83c\udfff", emptyList(), 40, 1),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udd90\ufe0f",
      shortcodes = listOf("raised_hand_with_fingers_splayed"),
      x = 32,
      y = 3,
      variants = listOf(
        TwitterEmoji("\ud83d\udd90\ud83c\udffb", emptyList(), 32, 4),
        TwitterEmoji("\ud83d\udd90\ud83c\udffc", emptyList(), 32, 5),
        TwitterEmoji("\ud83d\udd90\ud83c\udffd", emptyList(), 32, 6),
        TwitterEmoji("\ud83d\udd90\ud83c\udffe", emptyList(), 32, 7),
        TwitterEmoji("\ud83d\udd90\ud83c\udfff", emptyList(), 32, 8),
      ),
    ),
    TwitterEmoji(
      unicode = "\u270b",
      shortcodes = listOf("hand", "raised_hand"),
      x = 60,
      y = 8,
      variants = listOf(
        TwitterEmoji("\u270b\ud83c\udffb", emptyList(), 60, 9),
        TwitterEmoji("\u270b\ud83c\udffc", emptyList(), 60, 10),
        TwitterEmoji("\u270b\ud83c\udffd", emptyList(), 60, 11),
        TwitterEmoji("\u270b\ud83c\udffe", emptyList(), 60, 12),
        TwitterEmoji("\u270b\ud83c\udfff", emptyList(), 60, 13),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udd96",
      shortcodes = listOf("spock-hand"),
      x = 32,
      y = 15,
      variants = listOf(
        TwitterEmoji("\ud83d\udd96\ud83c\udffb", emptyList(), 32, 16),
        TwitterEmoji("\ud83d\udd96\ud83c\udffc", emptyList(), 32, 17),
        TwitterEmoji("\ud83d\udd96\ud83c\udffd", emptyList(), 32, 18),
        TwitterEmoji("\ud83d\udd96\ud83c\udffe", emptyList(), 32, 19),
        TwitterEmoji("\ud83d\udd96\ud83c\udfff", emptyList(), 32, 20),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef1",
      shortcodes = listOf("rightwards_hand"),
      x = 56,
      y = 53,
      variants = listOf(
        TwitterEmoji("\ud83e\udef1\ud83c\udffb", emptyList(), 56, 54),
        TwitterEmoji("\ud83e\udef1\ud83c\udffc", emptyList(), 56, 55),
        TwitterEmoji("\ud83e\udef1\ud83c\udffd", emptyList(), 56, 56),
        TwitterEmoji("\ud83e\udef1\ud83c\udffe", emptyList(), 56, 57),
        TwitterEmoji("\ud83e\udef1\ud83c\udfff", emptyList(), 56, 58),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef2",
      shortcodes = listOf("leftwards_hand"),
      x = 56,
      y = 59,
      variants = listOf(
        TwitterEmoji("\ud83e\udef2\ud83c\udffb", emptyList(), 56, 60),
        TwitterEmoji("\ud83e\udef2\ud83c\udffc", emptyList(), 56, 61),
        TwitterEmoji("\ud83e\udef2\ud83c\udffd", emptyList(), 57, 0),
        TwitterEmoji("\ud83e\udef2\ud83c\udffe", emptyList(), 57, 1),
        TwitterEmoji("\ud83e\udef2\ud83c\udfff", emptyList(), 57, 2),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef3",
      shortcodes = listOf("palm_down_hand"),
      x = 57,
      y = 3,
      variants = listOf(
        TwitterEmoji("\ud83e\udef3\ud83c\udffb", emptyList(), 57, 4),
        TwitterEmoji("\ud83e\udef3\ud83c\udffc", emptyList(), 57, 5),
        TwitterEmoji("\ud83e\udef3\ud83c\udffd", emptyList(), 57, 6),
        TwitterEmoji("\ud83e\udef3\ud83c\udffe", emptyList(), 57, 7),
        TwitterEmoji("\ud83e\udef3\ud83c\udfff", emptyList(), 57, 8),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef4",
      shortcodes = listOf("palm_up_hand"),
      x = 57,
      y = 9,
      variants = listOf(
        TwitterEmoji("\ud83e\udef4\ud83c\udffb", emptyList(), 57, 10),
        TwitterEmoji("\ud83e\udef4\ud83c\udffc", emptyList(), 57, 11),
        TwitterEmoji("\ud83e\udef4\ud83c\udffd", emptyList(), 57, 12),
        TwitterEmoji("\ud83e\udef4\ud83c\udffe", emptyList(), 57, 13),
        TwitterEmoji("\ud83e\udef4\ud83c\udfff", emptyList(), 57, 14),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef7",
      shortcodes = listOf("leftwards_pushing_hand"),
      x = 57,
      y = 27,
      variants = listOf(
        TwitterEmoji("\ud83e\udef7\ud83c\udffb", emptyList(), 57, 28),
        TwitterEmoji("\ud83e\udef7\ud83c\udffc", emptyList(), 57, 29),
        TwitterEmoji("\ud83e\udef7\ud83c\udffd", emptyList(), 57, 30),
        TwitterEmoji("\ud83e\udef7\ud83c\udffe", emptyList(), 57, 31),
        TwitterEmoji("\ud83e\udef7\ud83c\udfff", emptyList(), 57, 32),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef8",
      shortcodes = listOf("rightwards_pushing_hand"),
      x = 57,
      y = 33,
      variants = listOf(
        TwitterEmoji("\ud83e\udef8\ud83c\udffb", emptyList(), 57, 34),
        TwitterEmoji("\ud83e\udef8\ud83c\udffc", emptyList(), 57, 35),
        TwitterEmoji("\ud83e\udef8\ud83c\udffd", emptyList(), 57, 36),
        TwitterEmoji("\ud83e\udef8\ud83c\udffe", emptyList(), 57, 37),
        TwitterEmoji("\ud83e\udef8\ud83c\udfff", emptyList(), 57, 38),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc4c",
      shortcodes = listOf("ok_hand"),
      x = 12,
      y = 55,
      variants = listOf(
        TwitterEmoji("\ud83d\udc4c\ud83c\udffb", emptyList(), 12, 56),
        TwitterEmoji("\ud83d\udc4c\ud83c\udffc", emptyList(), 12, 57),
        TwitterEmoji("\ud83d\udc4c\ud83c\udffd", emptyList(), 12, 58),
        TwitterEmoji("\ud83d\udc4c\ud83c\udffe", emptyList(), 12, 59),
        TwitterEmoji("\ud83d\udc4c\ud83c\udfff", emptyList(), 12, 60),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd0c",
      shortcodes = listOf("pinched_fingers"),
      x = 39,
      y = 24,
      variants = listOf(
        TwitterEmoji("\ud83e\udd0c\ud83c\udffb", emptyList(), 39, 25),
        TwitterEmoji("\ud83e\udd0c\ud83c\udffc", emptyList(), 39, 26),
        TwitterEmoji("\ud83e\udd0c\ud83c\udffd", emptyList(), 39, 27),
        TwitterEmoji("\ud83e\udd0c\ud83c\udffe", emptyList(), 39, 28),
        TwitterEmoji("\ud83e\udd0c\ud83c\udfff", emptyList(), 39, 29),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd0f",
      shortcodes = listOf("pinching_hand"),
      x = 39,
      y = 32,
      variants = listOf(
        TwitterEmoji("\ud83e\udd0f\ud83c\udffb", emptyList(), 39, 33),
        TwitterEmoji("\ud83e\udd0f\ud83c\udffc", emptyList(), 39, 34),
        TwitterEmoji("\ud83e\udd0f\ud83c\udffd", emptyList(), 39, 35),
        TwitterEmoji("\ud83e\udd0f\ud83c\udffe", emptyList(), 39, 36),
        TwitterEmoji("\ud83e\udd0f\ud83c\udfff", emptyList(), 39, 37),
      ),
    ),
    TwitterEmoji(
      unicode = "\u270c\ufe0f",
      shortcodes = listOf("v"),
      x = 60,
      y = 14,
      variants = listOf(
        TwitterEmoji("\u270c\ud83c\udffb", emptyList(), 60, 15),
        TwitterEmoji("\u270c\ud83c\udffc", emptyList(), 60, 16),
        TwitterEmoji("\u270c\ud83c\udffd", emptyList(), 60, 17),
        TwitterEmoji("\u270c\ud83c\udffe", emptyList(), 60, 18),
        TwitterEmoji("\u270c\ud83c\udfff", emptyList(), 60, 19),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd1e",
      shortcodes = listOf("crossed_fingers", "hand_with_index_and_middle_fingers_crossed"),
      x = 40,
      y = 40,
      variants = listOf(
        TwitterEmoji("\ud83e\udd1e\ud83c\udffb", emptyList(), 40, 41),
        TwitterEmoji("\ud83e\udd1e\ud83c\udffc", emptyList(), 40, 42),
        TwitterEmoji("\ud83e\udd1e\ud83c\udffd", emptyList(), 40, 43),
        TwitterEmoji("\ud83e\udd1e\ud83c\udffe", emptyList(), 40, 44),
        TwitterEmoji("\ud83e\udd1e\ud83c\udfff", emptyList(), 40, 45),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef0",
      shortcodes = listOf("hand_with_index_finger_and_thumb_crossed"),
      x = 56,
      y = 47,
      variants = listOf(
        TwitterEmoji("\ud83e\udef0\ud83c\udffb", emptyList(), 56, 48),
        TwitterEmoji("\ud83e\udef0\ud83c\udffc", emptyList(), 56, 49),
        TwitterEmoji("\ud83e\udef0\ud83c\udffd", emptyList(), 56, 50),
        TwitterEmoji("\ud83e\udef0\ud83c\udffe", emptyList(), 56, 51),
        TwitterEmoji("\ud83e\udef0\ud83c\udfff", emptyList(), 56, 52),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd1f",
      shortcodes = listOf("i_love_you_hand_sign"),
      x = 40,
      y = 46,
      variants = listOf(
        TwitterEmoji("\ud83e\udd1f\ud83c\udffb", emptyList(), 40, 47),
        TwitterEmoji("\ud83e\udd1f\ud83c\udffc", emptyList(), 40, 48),
        TwitterEmoji("\ud83e\udd1f\ud83c\udffd", emptyList(), 40, 49),
        TwitterEmoji("\ud83e\udd1f\ud83c\udffe", emptyList(), 40, 50),
        TwitterEmoji("\ud83e\udd1f\ud83c\udfff", emptyList(), 40, 51),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd18",
      shortcodes = listOf("the_horns", "sign_of_the_horns"),
      x = 39,
      y = 46,
      variants = listOf(
        TwitterEmoji("\ud83e\udd18\ud83c\udffb", emptyList(), 39, 47),
        TwitterEmoji("\ud83e\udd18\ud83c\udffc", emptyList(), 39, 48),
        TwitterEmoji("\ud83e\udd18\ud83c\udffd", emptyList(), 39, 49),
        TwitterEmoji("\ud83e\udd18\ud83c\udffe", emptyList(), 39, 50),
        TwitterEmoji("\ud83e\udd18\ud83c\udfff", emptyList(), 39, 51),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udd19",
      shortcodes = listOf("call_me_hand"),
      x = 39,
      y = 52,
      variants = listOf(
        TwitterEmoji("\ud83e\udd19\ud83c\udffb", emptyList(), 39, 53),
        TwitterEmoji("\ud83e\udd19\ud83c\udffc", emptyList(), 39, 54),
        TwitterEmoji("\ud83e\udd19\ud83c\udffd", emptyList(), 39, 55),
        TwitterEmoji("\ud83e\udd19\ud83c\udffe", emptyList(), 39, 56),
        TwitterEmoji("\ud83e\udd19\ud83c\udfff", emptyList(), 39, 57),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc48",
      shortcodes = listOf("point_left"),
      x = 12,
      y = 31,
      variants = listOf(
        TwitterEmoji("\ud83d\udc48\ud83c\udffb", emptyList(), 12, 32),
        TwitterEmoji("\ud83d\udc48\ud83c\udffc", emptyList(), 12, 33),
        TwitterEmoji("\ud83d\udc48\ud83c\udffd", emptyList(), 12, 34),
        TwitterEmoji("\ud83d\udc48\ud83c\udffe", emptyList(), 12, 35),
        TwitterEmoji("\ud83d\udc48\ud83c\udfff", emptyList(), 12, 36),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc49",
      shortcodes = listOf("point_right"),
      x = 12,
      y = 37,
      variants = listOf(
        TwitterEmoji("\ud83d\udc49\ud83c\udffb", emptyList(), 12, 38),
        TwitterEmoji("\ud83d\udc49\ud83c\udffc", emptyList(), 12, 39),
        TwitterEmoji("\ud83d\udc49\ud83c\udffd", emptyList(), 12, 40),
        TwitterEmoji("\ud83d\udc49\ud83c\udffe", emptyList(), 12, 41),
        TwitterEmoji("\ud83d\udc49\ud83c\udfff", emptyList(), 12, 42),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc46",
      shortcodes = listOf("point_up_2"),
      x = 12,
      y = 19,
      variants = listOf(
        TwitterEmoji("\ud83d\udc46\ud83c\udffb", emptyList(), 12, 20),
        TwitterEmoji("\ud83d\udc46\ud83c\udffc", emptyList(), 12, 21),
        TwitterEmoji("\ud83d\udc46\ud83c\udffd", emptyList(), 12, 22),
        TwitterEmoji("\ud83d\udc46\ud83c\udffe", emptyList(), 12, 23),
        TwitterEmoji("\ud83d\udc46\ud83c\udfff", emptyList(), 12, 24),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udd95",
      shortcodes = listOf("middle_finger", "reversed_hand_with_middle_finger_extended"),
      x = 32,
      y = 9,
      variants = listOf(
        TwitterEmoji("\ud83d\udd95\ud83c\udffb", emptyList(), 32, 10),
        TwitterEmoji("\ud83d\udd95\ud83c\udffc", emptyList(), 32, 11),
        TwitterEmoji("\ud83d\udd95\ud83c\udffd", emptyList(), 32, 12),
        TwitterEmoji("\ud83d\udd95\ud83c\udffe", emptyList(), 32, 13),
        TwitterEmoji("\ud83d\udd95\ud83c\udfff", emptyList(), 32, 14),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc47",
      shortcodes = listOf("point_down"),
      x = 12,
      y = 25,
      variants = listOf(
        TwitterEmoji("\ud83d\udc47\ud83c\udffb", emptyList(), 12, 26),
        TwitterEmoji("\ud83d\udc47\ud83c\udffc", emptyList(), 12, 27),
        TwitterEmoji("\ud83d\udc47\ud83c\udffd", emptyList(), 12, 28),
        TwitterEmoji("\ud83d\udc47\ud83c\udffe", emptyList(), 12, 29),
        TwitterEmoji("\ud83d\udc47\ud83c\udfff", emptyList(), 12, 30),
      ),
    ),
    TwitterEmoji(
      unicode = "\u261d\ufe0f",
      shortcodes = listOf("point_up"),
      x = 58,
      y = 26,
      variants = listOf(
        TwitterEmoji("\u261d\ud83c\udffb", emptyList(), 58, 27),
        TwitterEmoji("\u261d\ud83c\udffc", emptyList(), 58, 28),
        TwitterEmoji("\u261d\ud83c\udffd", emptyList(), 58, 29),
        TwitterEmoji("\u261d\ud83c\udffe", emptyList(), 58, 30),
        TwitterEmoji("\u261d\ud83c\udfff", emptyList(), 58, 31),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83e\udef5",
      shortcodes = listOf("index_pointing_at_the_viewer"),
      x = 57,
      y = 15,
      variants = listOf(
        TwitterEmoji("\ud83e\udef5\ud83c\udffb", emptyList(), 57, 16),
        TwitterEmoji("\ud83e\udef5\ud83c\udffc", emptyList(), 57, 17),
        TwitterEmoji("\ud83e\udef5\ud83c\udffd", emptyList(), 57, 18),
        TwitterEmoji("\ud83e\udef5\ud83c\udffe", emptyList(), 57, 19),
        TwitterEmoji("\ud83e\udef5\ud83c\udfff", emptyList(), 57, 20),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc4d",
      shortcodes = listOf("+1", "thumbsup"),
      x = 12,
      y = 61,
      variants = listOf(
        TwitterEmoji("\ud83d\udc4d\ud83c\udffb", emptyList(), 13, 0),
        TwitterEmoji("\ud83d\udc4d\ud83c\udffc", emptyList(), 13, 1),
        TwitterEmoji("\ud83d\udc4d\ud83c\udffd", emptyList(), 13, 2),
        TwitterEmoji("\ud83d\udc4d\ud83c\udffe", emptyList(), 13, 3),
        TwitterEmoji("\ud83d\udc4d\ud83c\udfff", emptyList(), 13, 4),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc4e",
      shortcodes = listOf("-1", "thumbsdown"),
      x = 13,
      y = 5,
      variants = listOf(
        TwitterEmoji("\ud83d\udc4e\ud83c\udffb", emptyList(), 13, 6),
        TwitterEmoji("\ud83d\udc4e\ud83c\udffc", emptyList(), 13, 7),
        TwitterEmoji("\ud83d\udc4e\ud83c\udffd", emptyList(), 13, 8),
        TwitterEmoji("\ud83d\udc4e\ud83c\udffe", emptyList(), 13, 9),
        TwitterEmoji("\ud83d\udc4e\ud83c\udfff", emptyList(), 13, 10),
      ),
    ),
    TwitterEmoji(
      unicode = "\u270a",
      shortcodes = listOf("fist"),
      x = 60,
      y = 2,
      variants = listOf(
        TwitterEmoji("\u270a\ud83c\udffb", emptyList(), 60, 3),
        TwitterEmoji("\u270a\ud83c\udffc", emptyList(), 60, 4),
        TwitterEmoji("\u270a\ud83c\udffd", emptyList(), 60, 5),
        TwitterEmoji("\u270a\ud83c\udffe", emptyList(), 60, 6),
        TwitterEmoji("\u270a\ud83c\udfff", emptyList(), 60, 7),
      ),
    ),
    TwitterEmoji(
      unicode = "\ud83d\udc4a",
      shortcodes = listOf("facepunch", "punch"),
      x = 12,
      y = 43,
      variants = listOf(
        TwitterEmoji("\ud83d\udc4a\ud83c\udffb", emptyList(), 12, 44),
        TwitterEmoji("\ud83d\udc4a\ud83c\udffc", emptyList(), 12, 45),
        TwitterEmoji("\ud83d\udc4a\ud83c\udffd", emptyList(), 12, 46),
        TwitterEmoji("\ud83d\udc4a\ud83c\udffe", emptyList(), 12, 47),
        TwitterEmoji("\ud83d\udc4a\ud83c\udfff", emptyList(), 12, 48),
      ),
    ),
  )
}
