/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.facebook.category

import com.vanniktech.emoji.facebook.FacebookEmoji

internal object FoodAndDrinkCategoryChunk0 {
  internal val EMOJIS: List<FacebookEmoji> = listOf(
    FacebookEmoji("\ud83c\udf47", listOf("grapes"), 6, 3),
    FacebookEmoji("\ud83c\udf48", listOf("melon"), 6, 4),
    FacebookEmoji("\ud83c\udf49", listOf("watermelon"), 6, 5),
    FacebookEmoji("\ud83c\udf4a", listOf("tangerine"), 6, 6),
    FacebookEmoji("\ud83c\udf4b", listOf("lemon"), 6, 8),
    FacebookEmoji("\ud83c\udf4c", listOf("banana"), 6, 9),
    FacebookEmoji("\ud83c\udf4d", listOf("pineapple"), 6, 10),
    FacebookEmoji("\ud83e\udd6d", listOf("mango"), 44, 30),
    FacebookEmoji("\ud83c\udf4e", listOf("apple"), 6, 11),
    FacebookEmoji("\ud83c\udf4f", listOf("green_apple"), 6, 12),
    FacebookEmoji("\ud83c\udf50", listOf("pear"), 6, 13),
    FacebookEmoji("\ud83c\udf51", listOf("peach"), 6, 14),
    FacebookEmoji("\ud83c\udf52", listOf("cherries"), 6, 15),
    FacebookEmoji("\ud83c\udf53", listOf("strawberry"), 6, 16),
    FacebookEmoji("\ud83e\uded0", listOf("blueberries"), 56, 23),
    FacebookEmoji("\ud83e\udd5d", listOf("kiwifruit"), 44, 14),
    FacebookEmoji("\ud83c\udf45", listOf("tomato"), 6, 1),
    FacebookEmoji("\ud83e\uded2", listOf("olive"), 56, 25),
    FacebookEmoji("\ud83e\udd65", listOf("coconut"), 44, 22),
    FacebookEmoji("\ud83e\udd51", listOf("avocado"), 44, 2),
    FacebookEmoji("\ud83c\udf46", listOf("eggplant"), 6, 2),
    FacebookEmoji("\ud83e\udd54", listOf("potato"), 44, 5),
    FacebookEmoji("\ud83e\udd55", listOf("carrot"), 44, 6),
    FacebookEmoji("\ud83c\udf3d", listOf("corn"), 5, 54),
    FacebookEmoji(
      unicode = "\ud83c\udf36",
      shortcodes = listOf("hot_pepper"),
      x = 5,
      y = 47,
      variants = listOf(
        FacebookEmoji("\ud83c\udf36\ufe0f", emptyList(), 5, 47),
      ),
    ),
    FacebookEmoji("\ud83e\uded1", listOf("bell_pepper"), 56, 24),
    FacebookEmoji("\ud83e\udd52", listOf("cucumber"), 44, 3),
    FacebookEmoji("\ud83e\udd6c", listOf("leafy_green"), 44, 29),
    FacebookEmoji("\ud83e\udd66", listOf("broccoli"), 44, 23),
    FacebookEmoji("\ud83e\uddc4", listOf("garlic"), 46, 43),
    FacebookEmoji("\ud83e\uddc5", listOf("onion"), 46, 44),
    FacebookEmoji("\ud83e\udd5c", listOf("peanuts"), 44, 13),
    FacebookEmoji("\ud83e\uded8", listOf("beans"), 56, 31),
    FacebookEmoji("\ud83c\udf30", listOf("chestnut"), 5, 41),
    FacebookEmoji("\ud83e\udeda", listOf("ginger_root"), 56, 33),
    FacebookEmoji("\ud83e\udedb", listOf("pea_pod"), 56, 34),
    FacebookEmoji("\ud83c\udf5e", listOf("bread"), 6, 27),
    FacebookEmoji("\ud83e\udd50", listOf("croissant"), 44, 1),
    FacebookEmoji("\ud83e\udd56", listOf("baguette_bread"), 44, 7),
    FacebookEmoji("\ud83e\uded3", listOf("flatbread"), 56, 26),
    FacebookEmoji("\ud83e\udd68", listOf("pretzel"), 44, 25),
    FacebookEmoji("\ud83e\udd6f", listOf("bagel"), 44, 32),
    FacebookEmoji("\ud83e\udd5e", listOf("pancakes"), 44, 15),
    FacebookEmoji("\ud83e\uddc7", listOf("waffle"), 46, 46),
    FacebookEmoji("\ud83e\uddc0", listOf("cheese_wedge"), 46, 39),
    FacebookEmoji("\ud83c\udf56", listOf("meat_on_bone"), 6, 19),
    FacebookEmoji("\ud83c\udf57", listOf("poultry_leg"), 6, 20),
    FacebookEmoji("\ud83e\udd69", listOf("cut_of_meat"), 44, 26),
    FacebookEmoji("\ud83e\udd53", listOf("bacon"), 44, 4),
    FacebookEmoji("\ud83c\udf54", listOf("hamburger"), 6, 17),
    FacebookEmoji("\ud83c\udf5f", listOf("fries"), 6, 28),
    FacebookEmoji("\ud83c\udf55", listOf("pizza"), 6, 18),
    FacebookEmoji("\ud83c\udf2d", listOf("hotdog"), 5, 38),
    FacebookEmoji("\ud83e\udd6a", listOf("sandwich"), 44, 27),
    FacebookEmoji("\ud83c\udf2e", listOf("taco"), 5, 39),
    FacebookEmoji("\ud83c\udf2f", listOf("burrito"), 5, 40),
    FacebookEmoji("\ud83e\uded4", listOf("tamale"), 56, 27),
    FacebookEmoji("\ud83e\udd59", listOf("stuffed_flatbread"), 44, 10),
    FacebookEmoji("\ud83e\uddc6", listOf("falafel"), 46, 45),
    FacebookEmoji("\ud83e\udd5a", listOf("egg"), 44, 11),
    FacebookEmoji("\ud83c\udf73", listOf("fried_egg", "cooking"), 6, 48),
    FacebookEmoji("\ud83e\udd58", listOf("shallow_pan_of_food"), 44, 9),
    FacebookEmoji("\ud83c\udf72", listOf("stew"), 6, 47),
    FacebookEmoji("\ud83e\uded5", listOf("fondue"), 56, 28),
    FacebookEmoji("\ud83e\udd63", listOf("bowl_with_spoon"), 44, 20),
    FacebookEmoji("\ud83e\udd57", listOf("green_salad"), 44, 8),
    FacebookEmoji("\ud83c\udf7f", listOf("popcorn"), 6, 60),
    FacebookEmoji("\ud83e\uddc8", listOf("butter"), 46, 47),
    FacebookEmoji("\ud83e\uddc2", listOf("salt"), 46, 41),
    FacebookEmoji("\ud83e\udd6b", listOf("canned_food"), 44, 28),
    FacebookEmoji("\ud83c\udf71", listOf("bento"), 6, 46),
    FacebookEmoji("\ud83c\udf58", listOf("rice_cracker"), 6, 21),
    FacebookEmoji("\ud83c\udf59", listOf("rice_ball"), 6, 22),
    FacebookEmoji("\ud83c\udf5a", listOf("rice"), 6, 23),
    FacebookEmoji("\ud83c\udf5b", listOf("curry"), 6, 24),
    FacebookEmoji("\ud83c\udf5c", listOf("ramen"), 6, 25),
    FacebookEmoji("\ud83c\udf5d", listOf("spaghetti"), 6, 26),
    FacebookEmoji("\ud83c\udf60", listOf("sweet_potato"), 6, 29),
    FacebookEmoji("\ud83c\udf62", listOf("oden"), 6, 31),
    FacebookEmoji("\ud83c\udf63", listOf("sushi"), 6, 32),
    FacebookEmoji("\ud83c\udf64", listOf("fried_shrimp"), 6, 33),
    FacebookEmoji("\ud83c\udf65", listOf("fish_cake"), 6, 34),
    FacebookEmoji("\ud83e\udd6e", listOf("moon_cake"), 44, 31),
    FacebookEmoji("\ud83c\udf61", listOf("dango"), 6, 30),
    FacebookEmoji("\ud83e\udd5f", listOf("dumpling"), 44, 16),
    FacebookEmoji("\ud83e\udd60", listOf("fortune_cookie"), 44, 17),
    FacebookEmoji("\ud83e\udd61", listOf("takeout_box"), 44, 18),
    FacebookEmoji("\ud83c\udf66", listOf("icecream"), 6, 35),
    FacebookEmoji("\ud83c\udf67", listOf("shaved_ice"), 6, 36),
    FacebookEmoji("\ud83c\udf68", listOf("ice_cream"), 6, 37),
    FacebookEmoji("\ud83c\udf69", listOf("doughnut"), 6, 38),
    FacebookEmoji("\ud83c\udf6a", listOf("cookie"), 6, 39),
    FacebookEmoji("\ud83c\udf82", listOf("birthday"), 7, 1),
    FacebookEmoji("\ud83c\udf70", listOf("cake"), 6, 45),
    FacebookEmoji("\ud83e\uddc1", listOf("cupcake"), 46, 40),
    FacebookEmoji("\ud83e\udd67", listOf("pie"), 44, 24),
    FacebookEmoji("\ud83c\udf6b", listOf("chocolate_bar"), 6, 40),
    FacebookEmoji("\ud83c\udf6c", listOf("candy"), 6, 41),
    FacebookEmoji("\ud83c\udf6d", listOf("lollipop"), 6, 42),
    FacebookEmoji("\ud83c\udf6e", listOf("custard"), 6, 43),
  )
}
