/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.facebook.category

import com.vanniktech.emoji.facebook.FacebookEmoji

internal object ObjectsCategoryChunk0 {
  internal val EMOJIS: List<FacebookEmoji> = listOf(
    FacebookEmoji("\ud83d\udc53", listOf("eyeglasses"), 13, 25),
    FacebookEmoji("\ud83d\udd76\ufe0f", listOf("dark_sunglasses"), 31, 50),
    FacebookEmoji("\ud83e\udd7d", listOf("goggles"), 44, 51),
    FacebookEmoji("\ud83e\udd7c", listOf("lab_coat"), 44, 50),
    FacebookEmoji("\ud83e\uddba", listOf("safety_vest"), 46, 28),
    FacebookEmoji("\ud83d\udc54", listOf("necktie"), 13, 26),
    FacebookEmoji("\ud83d\udc55", listOf("shirt", "tshirt"), 13, 27),
    FacebookEmoji("\ud83d\udc56", listOf("jeans"), 13, 28),
    FacebookEmoji("\ud83e\udde3", listOf("scarf"), 54, 22),
    FacebookEmoji("\ud83e\udde4", listOf("gloves"), 54, 23),
    FacebookEmoji("\ud83e\udde5", listOf("coat"), 54, 24),
    FacebookEmoji("\ud83e\udde6", listOf("socks"), 54, 25),
    FacebookEmoji("\ud83d\udc57", listOf("dress"), 13, 29),
    FacebookEmoji("\ud83d\udc58", listOf("kimono"), 13, 30),
    FacebookEmoji("\ud83e\udd7b", listOf("sari"), 44, 49),
    FacebookEmoji("\ud83e\ude71", listOf("one-piece_swimsuit"), 54, 52),
    FacebookEmoji("\ud83e\ude72", listOf("briefs"), 54, 53),
    FacebookEmoji("\ud83e\ude73", listOf("shorts"), 54, 54),
    FacebookEmoji("\ud83d\udc59", listOf("bikini"), 13, 31),
    FacebookEmoji("\ud83d\udc5a", listOf("womans_clothes"), 13, 32),
    FacebookEmoji("\ud83e\udead", listOf("folding_hand_fan"), 55, 42),
    FacebookEmoji("\ud83d\udc5b", listOf("purse"), 13, 33),
    FacebookEmoji("\ud83d\udc5c", listOf("handbag"), 13, 34),
    FacebookEmoji("\ud83d\udc5d", listOf("pouch"), 13, 35),
    FacebookEmoji("\ud83d\udecd\ufe0f", listOf("shopping_bags"), 38, 40),
    FacebookEmoji("\ud83c\udf92", listOf("school_satchel"), 7, 22),
    FacebookEmoji("\ud83e\ude74", listOf("thong_sandal"), 54, 55),
    FacebookEmoji("\ud83d\udc5e", listOf("mans_shoe", "shoe"), 13, 36),
    FacebookEmoji("\ud83d\udc5f", listOf("athletic_shoe"), 13, 37),
    FacebookEmoji("\ud83e\udd7e", listOf("hiking_boot"), 44, 52),
    FacebookEmoji("\ud83e\udd7f", listOf("womans_flat_shoe"), 44, 53),
    FacebookEmoji("\ud83d\udc60", listOf("high_heel"), 13, 38),
    FacebookEmoji("\ud83d\udc61", listOf("sandal"), 13, 39),
    FacebookEmoji("\ud83e\ude70", listOf("ballet_shoes"), 54, 51),
    FacebookEmoji("\ud83d\udc62", listOf("boot"), 13, 40),
    FacebookEmoji("\ud83e\udeae", listOf("hair_pick"), 55, 43),
    FacebookEmoji("\ud83d\udc51", listOf("crown"), 13, 23),
    FacebookEmoji("\ud83d\udc52", listOf("womans_hat"), 13, 24),
    FacebookEmoji("\ud83c\udfa9", listOf("tophat"), 7, 40),
    FacebookEmoji("\ud83c\udf93", listOf("mortar_board"), 7, 23),
    FacebookEmoji("\ud83e\udde2", listOf("billed_cap"), 54, 21),
    FacebookEmoji("\ud83e\ude96", listOf("military_helmet"), 55, 19),
    FacebookEmoji("\u26d1\ufe0f", listOf("helmet_with_white_cross"), 59, 26),
    FacebookEmoji("\ud83d\udcff", listOf("prayer_beads"), 29, 54),
    FacebookEmoji("\ud83d\udc84", listOf("lipstick"), 26, 24),
    FacebookEmoji("\ud83d\udc8d", listOf("ring"), 27, 10),
    FacebookEmoji("\ud83d\udc8e", listOf("gem"), 27, 11),
    FacebookEmoji("\ud83d\udd07", listOf("mute"), 30, 0),
    FacebookEmoji("\ud83d\udd08", listOf("speaker"), 30, 1),
    FacebookEmoji("\ud83d\udd09", listOf("sound"), 30, 2),
    FacebookEmoji("\ud83d\udd0a", listOf("loud_sound"), 30, 3),
    FacebookEmoji("\ud83d\udce2", listOf("loudspeaker"), 29, 26),
    FacebookEmoji("\ud83d\udce3", listOf("mega"), 29, 27),
    FacebookEmoji("\ud83d\udcef", listOf("postal_horn"), 29, 39),
    FacebookEmoji("\ud83d\udd14", listOf("bell"), 30, 13),
    FacebookEmoji("\ud83d\udd15", listOf("no_bell"), 30, 14),
    FacebookEmoji("\ud83c\udfbc", listOf("musical_score"), 7, 59),
    FacebookEmoji("\ud83c\udfb5", listOf("musical_note"), 7, 52),
    FacebookEmoji("\ud83c\udfb6", listOf("notes"), 7, 53),
    FacebookEmoji("\ud83c\udf99\ufe0f", listOf("studio_microphone"), 7, 26),
    FacebookEmoji("\ud83c\udf9a\ufe0f", listOf("level_slider"), 7, 27),
    FacebookEmoji("\ud83c\udf9b\ufe0f", listOf("control_knobs"), 7, 28),
    FacebookEmoji("\ud83c\udfa4", listOf("microphone"), 7, 35),
    FacebookEmoji("\ud83c\udfa7", listOf("headphones"), 7, 38),
    FacebookEmoji("\ud83d\udcfb", listOf("radio"), 29, 51),
    FacebookEmoji("\ud83c\udfb7", listOf("saxophone"), 7, 54),
    FacebookEmoji("\ud83e\ude97", listOf("accordion"), 55, 20),
    FacebookEmoji("\ud83c\udfb8", listOf("guitar"), 7, 55),
    FacebookEmoji("\ud83c\udfb9", listOf("musical_keyboard"), 7, 56),
    FacebookEmoji("\ud83c\udfba", listOf("trumpet"), 7, 57),
    FacebookEmoji("\ud83c\udfbb", listOf("violin"), 7, 58),
    FacebookEmoji("\ud83e\ude95", listOf("banjo"), 55, 18),
    FacebookEmoji("\ud83e\udd41", listOf("drum_with_drumsticks"), 43, 49),
    FacebookEmoji("\ud83e\ude98", listOf("long_drum"), 55, 21),
    FacebookEmoji("\ud83e\ude87", listOf("maracas"), 55, 9),
    FacebookEmoji("\ud83e\ude88", listOf("flute"), 55, 10),
    FacebookEmoji("\ud83d\udcf1", listOf("iphone"), 29, 41),
    FacebookEmoji("\ud83d\udcf2", listOf("calling"), 29, 42),
    FacebookEmoji("\u260e\ufe0f", listOf("phone", "telephone"), 58, 21),
    FacebookEmoji("\ud83d\udcde", listOf("telephone_receiver"), 29, 22),
    FacebookEmoji("\ud83d\udcdf", listOf("pager"), 29, 23),
    FacebookEmoji("\ud83d\udce0", listOf("fax"), 29, 24),
    FacebookEmoji("\ud83d\udd0b", listOf("battery"), 30, 4),
    FacebookEmoji("\ud83e\udeab", listOf("low_battery"), 55, 40),
    FacebookEmoji("\ud83d\udd0c", listOf("electric_plug"), 30, 5),
    FacebookEmoji("\ud83d\udcbb", listOf("computer"), 28, 49),
    FacebookEmoji("\ud83d\udda5\ufe0f", listOf("desktop_computer"), 32, 22),
    FacebookEmoji("\ud83d\udda8\ufe0f", listOf("printer"), 32, 23),
    FacebookEmoji("\u2328\ufe0f", listOf("keyboard"), 57, 53),
    FacebookEmoji("\ud83d\uddb1\ufe0f", listOf("three_button_mouse"), 32, 24),
    FacebookEmoji("\ud83d\uddb2\ufe0f", listOf("trackball"), 32, 25),
    FacebookEmoji("\ud83d\udcbd", listOf("minidisc"), 28, 51),
    FacebookEmoji("\ud83d\udcbe", listOf("floppy_disk"), 28, 52),
    FacebookEmoji("\ud83d\udcbf", listOf("cd"), 28, 53),
    FacebookEmoji("\ud83d\udcc0", listOf("dvd"), 28, 54),
    FacebookEmoji("\ud83e\uddee", listOf("abacus"), 54, 33),
    FacebookEmoji("\ud83c\udfa5", listOf("movie_camera"), 7, 36),
    FacebookEmoji("\ud83c\udf9e\ufe0f", listOf("film_frames"), 7, 29),
    FacebookEmoji("\ud83d\udcfd\ufe0f", listOf("film_projector"), 29, 53),
    FacebookEmoji("\ud83c\udfac", listOf("clapper"), 7, 43),
  )
}
