/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.androidxemoji2.category

import com.vanniktech.emoji.androidxemoji2.AndroidxEmoji2

internal object FlagsCategoryChunk1 {
  internal val EMOJIS: List<AndroidxEmoji2> = listOf(
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddf5", listOf("flag-gp")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddf6", listOf("flag-gq")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddf7", listOf("flag-gr")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddf8", listOf("flag-gs")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddf9", listOf("flag-gt")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddfa", listOf("flag-gu")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddfc", listOf("flag-gw")),
    AndroidxEmoji2("\ud83c\uddec\ud83c\uddfe", listOf("flag-gy")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddf0", listOf("flag-hk")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddf2", listOf("flag-hm")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddf3", listOf("flag-hn")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddf7", listOf("flag-hr")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddf9", listOf("flag-ht")),
    AndroidxEmoji2("\ud83c\udded\ud83c\uddfa", listOf("flag-hu")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\udde8", listOf("flag-ic")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\udde9", listOf("flag-id")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddea", listOf("flag-ie")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf1", listOf("flag-il")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf2", listOf("flag-im")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf3", listOf("flag-in")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf4", listOf("flag-io")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf6", listOf("flag-iq")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf7", listOf("flag-ir")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf8", listOf("flag-is")),
    AndroidxEmoji2("\ud83c\uddee\ud83c\uddf9", listOf("it", "flag-it")),
    AndroidxEmoji2("\ud83c\uddef\ud83c\uddea", listOf("flag-je")),
    AndroidxEmoji2("\ud83c\uddef\ud83c\uddf2", listOf("flag-jm")),
    AndroidxEmoji2("\ud83c\uddef\ud83c\uddf4", listOf("flag-jo")),
    AndroidxEmoji2("\ud83c\uddef\ud83c\uddf5", listOf("jp", "flag-jp")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddea", listOf("flag-ke")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddec", listOf("flag-kg")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\udded", listOf("flag-kh")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddee", listOf("flag-ki")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddf2", listOf("flag-km")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddf3", listOf("flag-kn")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddf5", listOf("flag-kp")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddf7", listOf("kr", "flag-kr")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddfc", listOf("flag-kw")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddfe", listOf("flag-ky")),
    AndroidxEmoji2("\ud83c\uddf0\ud83c\uddff", listOf("flag-kz")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\udde6", listOf("flag-la")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\udde7", listOf("flag-lb")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\udde8", listOf("flag-lc")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddee", listOf("flag-li")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddf0", listOf("flag-lk")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddf7", listOf("flag-lr")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddf8", listOf("flag-ls")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddf9", listOf("flag-lt")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddfa", listOf("flag-lu")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddfb", listOf("flag-lv")),
    AndroidxEmoji2("\ud83c\uddf1\ud83c\uddfe", listOf("flag-ly")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\udde6", listOf("flag-ma")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\udde8", listOf("flag-mc")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\udde9", listOf("flag-md")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddea", listOf("flag-me")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddeb", listOf("flag-mf")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddec", listOf("flag-mg")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\udded", listOf("flag-mh")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf0", listOf("flag-mk")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf1", listOf("flag-ml")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf2", listOf("flag-mm")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf3", listOf("flag-mn")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf4", listOf("flag-mo")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf5", listOf("flag-mp")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf6", listOf("flag-mq")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf7", listOf("flag-mr")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf8", listOf("flag-ms")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddf9", listOf("flag-mt")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddfa", listOf("flag-mu")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddfb", listOf("flag-mv")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddfc", listOf("flag-mw")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddfd", listOf("flag-mx")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddfe", listOf("flag-my")),
    AndroidxEmoji2("\ud83c\uddf2\ud83c\uddff", listOf("flag-mz")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\udde6", listOf("flag-na")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\udde8", listOf("flag-nc")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddea", listOf("flag-ne")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddeb", listOf("flag-nf")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddec", listOf("flag-ng")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddee", listOf("flag-ni")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddf1", listOf("flag-nl")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddf4", listOf("flag-no")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddf5", listOf("flag-np")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddf7", listOf("flag-nr")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddfa", listOf("flag-nu")),
    AndroidxEmoji2("\ud83c\uddf3\ud83c\uddff", listOf("flag-nz")),
    AndroidxEmoji2("\ud83c\uddf4\ud83c\uddf2", listOf("flag-om")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\udde6", listOf("flag-pa")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddea", listOf("flag-pe")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddeb", listOf("flag-pf")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddec", listOf("flag-pg")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\udded", listOf("flag-ph")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf0", listOf("flag-pk")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf1", listOf("flag-pl")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf2", listOf("flag-pm")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf3", listOf("flag-pn")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf7", listOf("flag-pr")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf8", listOf("flag-ps")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddf9", listOf("flag-pt")),
    AndroidxEmoji2("\ud83c\uddf5\ud83c\uddfc", listOf("flag-pw")),
  )
}
