/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.androidxemoji2.category

import com.vanniktech.emoji.androidxemoji2.AndroidxEmoji2

internal object FoodAndDrinkCategoryChunk0 {
  internal val EMOJIS: List<AndroidxEmoji2> = listOf(
    AndroidxEmoji2(String(intArrayOf(0x1F347), 0, 1), listOf("grapes")),
    AndroidxEmoji2(String(intArrayOf(0x1F348), 0, 1), listOf("melon")),
    AndroidxEmoji2(String(intArrayOf(0x1F349), 0, 1), listOf("watermelon")),
    AndroidxEmoji2(String(intArrayOf(0x1F34A), 0, 1), listOf("tangerine")),
    AndroidxEmoji2(String(intArrayOf(0x1F34B), 0, 1), listOf("lemon")),
    AndroidxEmoji2(String(intArrayOf(0x1F34B, 0x200D, 0x1F7E9), 0, 3), listOf("lime")),
    AndroidxEmoji2(String(intArrayOf(0x1F34C), 0, 1), listOf("banana")),
    AndroidxEmoji2(String(intArrayOf(0x1F34D), 0, 1), listOf("pineapple")),
    AndroidxEmoji2(String(intArrayOf(0x1F96D), 0, 1), listOf("mango")),
    AndroidxEmoji2(String(intArrayOf(0x1F34E), 0, 1), listOf("apple")),
    AndroidxEmoji2(String(intArrayOf(0x1F34F), 0, 1), listOf("green_apple")),
    AndroidxEmoji2(String(intArrayOf(0x1F350), 0, 1), listOf("pear")),
    AndroidxEmoji2(String(intArrayOf(0x1F351), 0, 1), listOf("peach")),
    AndroidxEmoji2(String(intArrayOf(0x1F352), 0, 1), listOf("cherries")),
    AndroidxEmoji2(String(intArrayOf(0x1F353), 0, 1), listOf("strawberry")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD0), 0, 1), listOf("blueberries")),
    AndroidxEmoji2(String(intArrayOf(0x1F95D), 0, 1), listOf("kiwifruit")),
    AndroidxEmoji2(String(intArrayOf(0x1F345), 0, 1), listOf("tomato")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD2), 0, 1), listOf("olive")),
    AndroidxEmoji2(String(intArrayOf(0x1F965), 0, 1), listOf("coconut")),
    AndroidxEmoji2(String(intArrayOf(0x1F951), 0, 1), listOf("avocado")),
    AndroidxEmoji2(String(intArrayOf(0x1F346), 0, 1), listOf("eggplant")),
    AndroidxEmoji2(String(intArrayOf(0x1F954), 0, 1), listOf("potato")),
    AndroidxEmoji2(String(intArrayOf(0x1F955), 0, 1), listOf("carrot")),
    AndroidxEmoji2(String(intArrayOf(0x1F33D), 0, 1), listOf("corn")),
    AndroidxEmoji2(
      String(intArrayOf(0x1F336), 0, 1), listOf("hot_pepper"),
      variants = listOf(
        AndroidxEmoji2(String(intArrayOf(0x1F336, 0xFE0F), 0, 2), emptyList<String>()),
      ),
    ),
    AndroidxEmoji2(String(intArrayOf(0x1FAD1), 0, 1), listOf("bell_pepper")),
    AndroidxEmoji2(String(intArrayOf(0x1F952), 0, 1), listOf("cucumber")),
    AndroidxEmoji2(String(intArrayOf(0x1F96C), 0, 1), listOf("leafy_green")),
    AndroidxEmoji2(String(intArrayOf(0x1F966), 0, 1), listOf("broccoli")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C4), 0, 1), listOf("garlic")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C5), 0, 1), listOf("onion")),
    AndroidxEmoji2(String(intArrayOf(0x1F95C), 0, 1), listOf("peanuts")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD8), 0, 1), listOf("beans")),
    AndroidxEmoji2(String(intArrayOf(0x1F330), 0, 1), listOf("chestnut")),
    AndroidxEmoji2(String(intArrayOf(0x1FADA), 0, 1), listOf("ginger_root")),
    AndroidxEmoji2(String(intArrayOf(0x1FADB), 0, 1), listOf("pea_pod")),
    AndroidxEmoji2(String(intArrayOf(0x1F344, 0x200D, 0x1F7EB), 0, 3), listOf("brown_mushroom")),
    AndroidxEmoji2(String(intArrayOf(0x1F35E), 0, 1), listOf("bread")),
    AndroidxEmoji2(String(intArrayOf(0x1F950), 0, 1), listOf("croissant")),
    AndroidxEmoji2(String(intArrayOf(0x1F956), 0, 1), listOf("baguette_bread")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD3), 0, 1), listOf("flatbread")),
    AndroidxEmoji2(String(intArrayOf(0x1F968), 0, 1), listOf("pretzel")),
    AndroidxEmoji2(String(intArrayOf(0x1F96F), 0, 1), listOf("bagel")),
    AndroidxEmoji2(String(intArrayOf(0x1F95E), 0, 1), listOf("pancakes")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C7), 0, 1), listOf("waffle")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C0), 0, 1), listOf("cheese_wedge")),
    AndroidxEmoji2(String(intArrayOf(0x1F356), 0, 1), listOf("meat_on_bone")),
    AndroidxEmoji2(String(intArrayOf(0x1F357), 0, 1), listOf("poultry_leg")),
    AndroidxEmoji2(String(intArrayOf(0x1F969), 0, 1), listOf("cut_of_meat")),
    AndroidxEmoji2(String(intArrayOf(0x1F953), 0, 1), listOf("bacon")),
    AndroidxEmoji2(String(intArrayOf(0x1F354), 0, 1), listOf("hamburger")),
    AndroidxEmoji2(String(intArrayOf(0x1F35F), 0, 1), listOf("fries")),
    AndroidxEmoji2(String(intArrayOf(0x1F355), 0, 1), listOf("pizza")),
    AndroidxEmoji2(String(intArrayOf(0x1F32D), 0, 1), listOf("hotdog")),
    AndroidxEmoji2(String(intArrayOf(0x1F96A), 0, 1), listOf("sandwich")),
    AndroidxEmoji2(String(intArrayOf(0x1F32E), 0, 1), listOf("taco")),
    AndroidxEmoji2(String(intArrayOf(0x1F32F), 0, 1), listOf("burrito")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD4), 0, 1), listOf("tamale")),
    AndroidxEmoji2(String(intArrayOf(0x1F959), 0, 1), listOf("stuffed_flatbread")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C6), 0, 1), listOf("falafel")),
    AndroidxEmoji2(String(intArrayOf(0x1F95A), 0, 1), listOf("egg")),
    AndroidxEmoji2(String(intArrayOf(0x1F373), 0, 1), listOf("fried_egg", "cooking")),
    AndroidxEmoji2(String(intArrayOf(0x1F958), 0, 1), listOf("shallow_pan_of_food")),
    AndroidxEmoji2(String(intArrayOf(0x1F372), 0, 1), listOf("stew")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD5), 0, 1), listOf("fondue")),
    AndroidxEmoji2(String(intArrayOf(0x1F963), 0, 1), listOf("bowl_with_spoon")),
    AndroidxEmoji2(String(intArrayOf(0x1F957), 0, 1), listOf("green_salad")),
    AndroidxEmoji2(String(intArrayOf(0x1F37F), 0, 1), listOf("popcorn")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C8), 0, 1), listOf("butter")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C2), 0, 1), listOf("salt")),
    AndroidxEmoji2(String(intArrayOf(0x1F96B), 0, 1), listOf("canned_food")),
    AndroidxEmoji2(String(intArrayOf(0x1F371), 0, 1), listOf("bento")),
    AndroidxEmoji2(String(intArrayOf(0x1F358), 0, 1), listOf("rice_cracker")),
    AndroidxEmoji2(String(intArrayOf(0x1F359), 0, 1), listOf("rice_ball")),
    AndroidxEmoji2(String(intArrayOf(0x1F35A), 0, 1), listOf("rice")),
    AndroidxEmoji2(String(intArrayOf(0x1F35B), 0, 1), listOf("curry")),
    AndroidxEmoji2(String(intArrayOf(0x1F35C), 0, 1), listOf("ramen")),
    AndroidxEmoji2(String(intArrayOf(0x1F35D), 0, 1), listOf("spaghetti")),
    AndroidxEmoji2(String(intArrayOf(0x1F360), 0, 1), listOf("sweet_potato")),
    AndroidxEmoji2(String(intArrayOf(0x1F362), 0, 1), listOf("oden")),
    AndroidxEmoji2(String(intArrayOf(0x1F363), 0, 1), listOf("sushi")),
    AndroidxEmoji2(String(intArrayOf(0x1F364), 0, 1), listOf("fried_shrimp")),
    AndroidxEmoji2(String(intArrayOf(0x1F365), 0, 1), listOf("fish_cake")),
    AndroidxEmoji2(String(intArrayOf(0x1F96E), 0, 1), listOf("moon_cake")),
    AndroidxEmoji2(String(intArrayOf(0x1F361), 0, 1), listOf("dango")),
    AndroidxEmoji2(String(intArrayOf(0x1F95F), 0, 1), listOf("dumpling")),
    AndroidxEmoji2(String(intArrayOf(0x1F960), 0, 1), listOf("fortune_cookie")),
    AndroidxEmoji2(String(intArrayOf(0x1F961), 0, 1), listOf("takeout_box")),
    AndroidxEmoji2(String(intArrayOf(0x1F980), 0, 1), listOf("crab")),
    AndroidxEmoji2(String(intArrayOf(0x1F99E), 0, 1), listOf("lobster")),
    AndroidxEmoji2(String(intArrayOf(0x1F990), 0, 1), listOf("shrimp")),
    AndroidxEmoji2(String(intArrayOf(0x1F991), 0, 1), listOf("squid")),
    AndroidxEmoji2(String(intArrayOf(0x1F9AA), 0, 1), listOf("oyster")),
    AndroidxEmoji2(String(intArrayOf(0x1F366), 0, 1), listOf("icecream")),
    AndroidxEmoji2(String(intArrayOf(0x1F367), 0, 1), listOf("shaved_ice")),
    AndroidxEmoji2(String(intArrayOf(0x1F368), 0, 1), listOf("ice_cream")),
    AndroidxEmoji2(String(intArrayOf(0x1F369), 0, 1), listOf("doughnut")),
    AndroidxEmoji2(String(intArrayOf(0x1F36A), 0, 1), listOf("cookie")),
    AndroidxEmoji2(String(intArrayOf(0x1F382), 0, 1), listOf("birthday")),
    AndroidxEmoji2(String(intArrayOf(0x1F370), 0, 1), listOf("cake")),
    AndroidxEmoji2(String(intArrayOf(0x1F9C1), 0, 1), listOf("cupcake")),
    AndroidxEmoji2(String(intArrayOf(0x1F967), 0, 1), listOf("pie")),
    AndroidxEmoji2(String(intArrayOf(0x1F36B), 0, 1), listOf("chocolate_bar")),
    AndroidxEmoji2(String(intArrayOf(0x1F36C), 0, 1), listOf("candy")),
    AndroidxEmoji2(String(intArrayOf(0x1F36D), 0, 1), listOf("lollipop")),
    AndroidxEmoji2(String(intArrayOf(0x1F36E), 0, 1), listOf("custard")),
    AndroidxEmoji2(String(intArrayOf(0x1F36F), 0, 1), listOf("honey_pot")),
    AndroidxEmoji2(String(intArrayOf(0x1F37C), 0, 1), listOf("baby_bottle")),
    AndroidxEmoji2(String(intArrayOf(0x1F95B), 0, 1), listOf("glass_of_milk")),
    AndroidxEmoji2(String(intArrayOf(0x2615), 0, 1), listOf("coffee")),
    AndroidxEmoji2(String(intArrayOf(0x1FAD6), 0, 1), listOf("teapot")),
    AndroidxEmoji2(String(intArrayOf(0x1F375), 0, 1), listOf("tea")),
    AndroidxEmoji2(String(intArrayOf(0x1F376), 0, 1), listOf("sake")),
    AndroidxEmoji2(String(intArrayOf(0x1F37E), 0, 1), listOf("champagne")),
    AndroidxEmoji2(String(intArrayOf(0x1F377), 0, 1), listOf("wine_glass")),
    AndroidxEmoji2(String(intArrayOf(0x1F378), 0, 1), listOf("cocktail")),
    AndroidxEmoji2(String(intArrayOf(0x1F379), 0, 1), listOf("tropical_drink")),
    AndroidxEmoji2(String(intArrayOf(0x1F37A), 0, 1), listOf("beer")),
    AndroidxEmoji2(String(intArrayOf(0x1F37B), 0, 1), listOf("beers")),
  )
}
