/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.androidxemoji2.category

import com.vanniktech.emoji.androidxemoji2.AndroidxEmoji2

internal object ObjectsCategoryChunk0 {
  internal val EMOJIS: List<AndroidxEmoji2> = listOf(
    AndroidxEmoji2(String(intArrayOf(0x1F453), 0, 1), listOf("eyeglasses"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F576, 0xFE0F), 0, 2), listOf("dark_sunglasses"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F97D), 0, 1), listOf("goggles"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F97C), 0, 1), listOf("lab_coat"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9BA), 0, 1), listOf("safety_vest"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F454), 0, 1), listOf("necktie"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F455), 0, 1), listOf("shirt", "tshirt"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F456), 0, 1), listOf("jeans"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9E3), 0, 1), listOf("scarf"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9E4), 0, 1), listOf("gloves"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9E5), 0, 1), listOf("coat"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9E6), 0, 1), listOf("socks"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F457), 0, 1), listOf("dress"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F458), 0, 1), listOf("kimono"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F97B), 0, 1), listOf("sari"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA71), 0, 1), listOf("one-piece_swimsuit"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA72), 0, 1), listOf("briefs"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA73), 0, 1), listOf("shorts"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F459), 0, 1), listOf("bikini"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45A), 0, 1), listOf("womans_clothes"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FAAD), 0, 1), listOf("folding_hand_fan"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45B), 0, 1), listOf("purse"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45C), 0, 1), listOf("handbag"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45D), 0, 1), listOf("pouch"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F6CD, 0xFE0F), 0, 2), listOf("shopping_bags"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F392), 0, 1), listOf("school_satchel"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA74), 0, 1), listOf("thong_sandal"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45E), 0, 1), listOf("mans_shoe", "shoe"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F45F), 0, 1), listOf("athletic_shoe"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F97E), 0, 1), listOf("hiking_boot"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F97F), 0, 1), listOf("womans_flat_shoe"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F460), 0, 1), listOf("high_heel"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F461), 0, 1), listOf("sandal"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA70), 0, 1), listOf("ballet_shoes"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F462), 0, 1), listOf("boot"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FAAE), 0, 1), listOf("hair_pick"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F451), 0, 1), listOf("crown"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F452), 0, 1), listOf("womans_hat"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3A9), 0, 1), listOf("tophat"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F393), 0, 1), listOf("mortar_board"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9E2), 0, 1), listOf("billed_cap"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA96), 0, 1), listOf("military_helmet"), false),
    AndroidxEmoji2(String(intArrayOf(0x26D1, 0xFE0F), 0, 2), listOf("helmet_with_white_cross"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4FF), 0, 1), listOf("prayer_beads"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F484), 0, 1), listOf("lipstick"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F48D), 0, 1), listOf("ring"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F48E), 0, 1), listOf("gem"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F507), 0, 1), listOf("mute"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F508), 0, 1), listOf("speaker"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F509), 0, 1), listOf("sound"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F50A), 0, 1), listOf("loud_sound"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4E2), 0, 1), listOf("loudspeaker"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4E3), 0, 1), listOf("mega"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4EF), 0, 1), listOf("postal_horn"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F514), 0, 1), listOf("bell"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F515), 0, 1), listOf("no_bell"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3BC), 0, 1), listOf("musical_score"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3B5), 0, 1), listOf("musical_note"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3B6), 0, 1), listOf("notes"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F399, 0xFE0F), 0, 2), listOf("studio_microphone"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F39A, 0xFE0F), 0, 2), listOf("level_slider"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F39B, 0xFE0F), 0, 2), listOf("control_knobs"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3A4), 0, 1), listOf("microphone"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3A7), 0, 1), listOf("headphones"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4FB), 0, 1), listOf("radio"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3B7), 0, 1), listOf("saxophone"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA97), 0, 1), listOf("accordion"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3B8), 0, 1), listOf("guitar"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3B9), 0, 1), listOf("musical_keyboard"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3BA), 0, 1), listOf("trumpet"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3BB), 0, 1), listOf("violin"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA95), 0, 1), listOf("banjo"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F941), 0, 1), listOf("drum_with_drumsticks"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA98), 0, 1), listOf("long_drum"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA87), 0, 1), listOf("maracas"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA88), 0, 1), listOf("flute"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4F1), 0, 1), listOf("iphone"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4F2), 0, 1), listOf("calling"), false),
    AndroidxEmoji2(String(intArrayOf(0x260E, 0xFE0F), 0, 2), listOf("phone", "telephone"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4DE), 0, 1), listOf("telephone_receiver"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4DF), 0, 1), listOf("pager"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4E0), 0, 1), listOf("fax"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F50B), 0, 1), listOf("battery"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FAAB), 0, 1), listOf("low_battery"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F50C), 0, 1), listOf("electric_plug"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4BB), 0, 1), listOf("computer"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F5A5, 0xFE0F), 0, 2), listOf("desktop_computer"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F5A8, 0xFE0F), 0, 2), listOf("printer"), false),
    AndroidxEmoji2(String(intArrayOf(0x2328, 0xFE0F), 0, 2), listOf("keyboard"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F5B1, 0xFE0F), 0, 2), listOf("three_button_mouse"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F5B2, 0xFE0F), 0, 2), listOf("trackball"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4BD), 0, 1), listOf("minidisc"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4BE), 0, 1), listOf("floppy_disk"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4BF), 0, 1), listOf("cd"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4C0), 0, 1), listOf("dvd"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F9EE), 0, 1), listOf("abacus"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3A5), 0, 1), listOf("movie_camera"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F39E, 0xFE0F), 0, 2), listOf("film_frames"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4FD, 0xFE0F), 0, 2), listOf("film_projector"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3AC), 0, 1), listOf("clapper"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4FA), 0, 1), listOf("tv"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4F7), 0, 1), listOf("camera"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4F8), 0, 1), listOf("camera_with_flash"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4F9), 0, 1), listOf("video_camera"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4FC), 0, 1), listOf("vhs"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F50D), 0, 1), listOf("mag"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F50E), 0, 1), listOf("mag_right"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F56F, 0xFE0F), 0, 2), listOf("candle"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4A1), 0, 1), listOf("bulb"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F526), 0, 1), listOf("flashlight"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F3EE), 0, 1), listOf("izakaya_lantern", "lantern"), false),
    AndroidxEmoji2(String(intArrayOf(0x1FA94), 0, 1), listOf("diya_lamp"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D4), 0, 1), listOf("notebook_with_decorative_cover"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D5), 0, 1), listOf("closed_book"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D6), 0, 1), listOf("book", "open_book"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D7), 0, 1), listOf("green_book"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D8), 0, 1), listOf("blue_book"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D9), 0, 1), listOf("orange_book"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4DA), 0, 1), listOf("books"), false),
    AndroidxEmoji2(String(intArrayOf(0x1F4D3), 0, 1), listOf("notebook"), false),
  )
}
