package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class ActivitiesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F383, "jack_o_lantern", false),
      new GoogleCompatEmoji(0x1F384, "christmas_tree", false),
      new GoogleCompatEmoji(0x1F386, "fireworks", false),
      new GoogleCompatEmoji(0x1F387, "sparkler", false),
      new GoogleCompatEmoji(0x1F9E8, "firecracker", false),
      new GoogleCompatEmoji(0x2728, "sparkles", false),
      new GoogleCompatEmoji(0x1F388, "balloon", false),
      new GoogleCompatEmoji(0x1F389, "tada", false),
      new GoogleCompatEmoji(0x1F38A, "confetti_ball", false),
      new GoogleCompatEmoji(0x1F38B, "tanabata_tree", false),
      new GoogleCompatEmoji(0x1F38D, "bamboo", false),
      new GoogleCompatEmoji(0x1F38E, "dolls", false),
      new GoogleCompatEmoji(0x1F38F, "flags", false),
      new GoogleCompatEmoji(0x1F390, "wind_chime", false),
      new GoogleCompatEmoji(0x1F391, "rice_scene", false),
      new GoogleCompatEmoji(0x1F9E7, "red_envelope", false),
      new GoogleCompatEmoji(0x1F380, "ribbon", false),
      new GoogleCompatEmoji(0x1F381, "gift", false),
      new GoogleCompatEmoji(new int[] { 0x1F397, 0xFE0F }, "reminder_ribbon", false),
      new GoogleCompatEmoji(new int[] { 0x1F39F, 0xFE0F }, "admission_tickets", false),
      new GoogleCompatEmoji(0x1F3AB, "ticket", false),
      new GoogleCompatEmoji(new int[] { 0x1F396, 0xFE0F }, "medal", false),
      new GoogleCompatEmoji(0x1F3C6, "trophy", false),
      new GoogleCompatEmoji(0x1F3C5, "sports_medal", false),
      new GoogleCompatEmoji(0x1F947, "first_place_medal", false),
      new GoogleCompatEmoji(0x1F948, "second_place_medal", false),
      new GoogleCompatEmoji(0x1F949, "third_place_medal", false),
      new GoogleCompatEmoji(0x26BD, "soccer", false),
      new GoogleCompatEmoji(0x26BE, "baseball", false),
      new GoogleCompatEmoji(0x1F94E, "softball", false),
      new GoogleCompatEmoji(0x1F3C0, "basketball", false),
      new GoogleCompatEmoji(0x1F3D0, "volleyball", false),
      new GoogleCompatEmoji(0x1F3C8, "football", false),
      new GoogleCompatEmoji(0x1F3C9, "rugby_football", false),
      new GoogleCompatEmoji(0x1F3BE, "tennis", false),
      new GoogleCompatEmoji(0x1F94F, "flying_disc", false),
      new GoogleCompatEmoji(0x1F3B3, "bowling", false),
      new GoogleCompatEmoji(0x1F3CF, "cricket_bat_and_ball", false),
      new GoogleCompatEmoji(0x1F3D1, "field_hockey_stick_and_ball", false),
      new GoogleCompatEmoji(0x1F3D2, "ice_hockey_stick_and_puck", false),
      new GoogleCompatEmoji(0x1F94D, "lacrosse", false),
      new GoogleCompatEmoji(0x1F3D3, "table_tennis_paddle_and_ball", false),
      new GoogleCompatEmoji(0x1F3F8, "badminton_racquet_and_shuttlecock", false),
      new GoogleCompatEmoji(0x1F94A, "boxing_glove", false),
      new GoogleCompatEmoji(0x1F94B, "martial_arts_uniform", false),
      new GoogleCompatEmoji(0x1F945, "goal_net", false),
      new GoogleCompatEmoji(0x26F3, "golf", false),
      new GoogleCompatEmoji(new int[] { 0x26F8, 0xFE0F }, "ice_skate", false),
      new GoogleCompatEmoji(0x1F3A3, "fishing_pole_and_fish", false),
      new GoogleCompatEmoji(0x1F93F, "diving_mask", false),
      new GoogleCompatEmoji(0x1F3BD, "running_shirt_with_sash", false),
      new GoogleCompatEmoji(0x1F3BF, "ski", false),
      new GoogleCompatEmoji(0x1F6F7, "sled", false),
      new GoogleCompatEmoji(0x1F94C, "curling_stone", false),
      new GoogleCompatEmoji(0x1F3AF, "dart", false),
      new GoogleCompatEmoji(0x1FA80, "yo-yo", false),
      new GoogleCompatEmoji(0x1FA81, "kite", false),
      new GoogleCompatEmoji(0x1F3B1, "8ball", false),
      new GoogleCompatEmoji(0x1F52E, "crystal_ball", false),
      new GoogleCompatEmoji(0x1F9FF, "nazar_amulet", false),
      new GoogleCompatEmoji(0x1F3AE, "video_game", false),
      new GoogleCompatEmoji(new int[] { 0x1F579, 0xFE0F }, "joystick", false),
      new GoogleCompatEmoji(0x1F3B0, "slot_machine", false),
      new GoogleCompatEmoji(0x1F3B2, "game_die", false),
      new GoogleCompatEmoji(0x1F9E9, "jigsaw", false),
      new GoogleCompatEmoji(0x1F9F8, "teddy_bear", false),
      new GoogleCompatEmoji(new int[] { 0x2660, 0xFE0F }, "spades", false),
      new GoogleCompatEmoji(new int[] { 0x2665, 0xFE0F }, "hearts", false),
      new GoogleCompatEmoji(new int[] { 0x2666, 0xFE0F }, "diamonds", false),
      new GoogleCompatEmoji(new int[] { 0x2663, 0xFE0F }, "clubs", false),
      new GoogleCompatEmoji(new int[] { 0x265F, 0xFE0F }, "chess_pawn", false),
      new GoogleCompatEmoji(0x1F0CF, "black_joker", false),
      new GoogleCompatEmoji(0x1F004, "mahjong", false),
      new GoogleCompatEmoji(0x1F3B4, "flower_playing_cards", false),
      new GoogleCompatEmoji(0x1F3AD, "performing_arts", false),
      new GoogleCompatEmoji(new int[] { 0x1F5BC, 0xFE0F }, "frame_with_picture", false),
      new GoogleCompatEmoji(0x1F3A8, "art", false),
      new GoogleCompatEmoji(0x1F9F5, "thread", false),
      new GoogleCompatEmoji(0x1F9F6, "yarn", false)
    };
  }

  private ActivitiesCategoryChunk0() {
    // No instances.
  }
}
