/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object FoodAndDrinkCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji("\ud83c\udf47", listOf("grapes")),
    GoogleCompatEmoji("\ud83c\udf48", listOf("melon")),
    GoogleCompatEmoji("\ud83c\udf49", listOf("watermelon")),
    GoogleCompatEmoji("\ud83c\udf4a", listOf("tangerine")),
    GoogleCompatEmoji("\ud83c\udf4b", listOf("lemon")),
    GoogleCompatEmoji("\ud83c\udf4b\u200d\ud83d\udfe9", listOf("lime")),
    GoogleCompatEmoji("\ud83c\udf4c", listOf("banana")),
    GoogleCompatEmoji("\ud83c\udf4d", listOf("pineapple")),
    GoogleCompatEmoji("\ud83e\udd6d", listOf("mango")),
    GoogleCompatEmoji("\ud83c\udf4e", listOf("apple")),
    GoogleCompatEmoji("\ud83c\udf4f", listOf("green_apple")),
    GoogleCompatEmoji("\ud83c\udf50", listOf("pear")),
    GoogleCompatEmoji("\ud83c\udf51", listOf("peach")),
    GoogleCompatEmoji("\ud83c\udf52", listOf("cherries")),
    GoogleCompatEmoji("\ud83c\udf53", listOf("strawberry")),
    GoogleCompatEmoji("\ud83e\uded0", listOf("blueberries")),
    GoogleCompatEmoji("\ud83e\udd5d", listOf("kiwifruit")),
    GoogleCompatEmoji("\ud83c\udf45", listOf("tomato")),
    GoogleCompatEmoji("\ud83e\uded2", listOf("olive")),
    GoogleCompatEmoji("\ud83e\udd65", listOf("coconut")),
    GoogleCompatEmoji("\ud83e\udd51", listOf("avocado")),
    GoogleCompatEmoji("\ud83c\udf46", listOf("eggplant")),
    GoogleCompatEmoji("\ud83e\udd54", listOf("potato")),
    GoogleCompatEmoji("\ud83e\udd55", listOf("carrot")),
    GoogleCompatEmoji("\ud83c\udf3d", listOf("corn")),
    GoogleCompatEmoji(
      unicode = "\ud83c\udf36",
      shortcodes = listOf("hot_pepper"),
      variants = listOf(
        GoogleCompatEmoji("\ud83c\udf36\ufe0f", emptyList()),
      ),
    ),
    GoogleCompatEmoji("\ud83e\uded1", listOf("bell_pepper")),
    GoogleCompatEmoji("\ud83e\udd52", listOf("cucumber")),
    GoogleCompatEmoji("\ud83e\udd6c", listOf("leafy_green")),
    GoogleCompatEmoji("\ud83e\udd66", listOf("broccoli")),
    GoogleCompatEmoji("\ud83e\uddc4", listOf("garlic")),
    GoogleCompatEmoji("\ud83e\uddc5", listOf("onion")),
    GoogleCompatEmoji("\ud83e\udd5c", listOf("peanuts")),
    GoogleCompatEmoji("\ud83e\uded8", listOf("beans")),
    GoogleCompatEmoji("\ud83c\udf30", listOf("chestnut")),
    GoogleCompatEmoji("\ud83e\udeda", listOf("ginger_root")),
    GoogleCompatEmoji("\ud83e\udedb", listOf("pea_pod")),
    GoogleCompatEmoji("\ud83c\udf44\u200d\ud83d\udfeb", listOf("brown_mushroom")),
    GoogleCompatEmoji("\ud83c\udf5e", listOf("bread")),
    GoogleCompatEmoji("\ud83e\udd50", listOf("croissant")),
    GoogleCompatEmoji("\ud83e\udd56", listOf("baguette_bread")),
    GoogleCompatEmoji("\ud83e\uded3", listOf("flatbread")),
    GoogleCompatEmoji("\ud83e\udd68", listOf("pretzel")),
    GoogleCompatEmoji("\ud83e\udd6f", listOf("bagel")),
    GoogleCompatEmoji("\ud83e\udd5e", listOf("pancakes")),
    GoogleCompatEmoji("\ud83e\uddc7", listOf("waffle")),
    GoogleCompatEmoji("\ud83e\uddc0", listOf("cheese_wedge")),
    GoogleCompatEmoji("\ud83c\udf56", listOf("meat_on_bone")),
    GoogleCompatEmoji("\ud83c\udf57", listOf("poultry_leg")),
    GoogleCompatEmoji("\ud83e\udd69", listOf("cut_of_meat")),
    GoogleCompatEmoji("\ud83e\udd53", listOf("bacon")),
    GoogleCompatEmoji("\ud83c\udf54", listOf("hamburger")),
    GoogleCompatEmoji("\ud83c\udf5f", listOf("fries")),
    GoogleCompatEmoji("\ud83c\udf55", listOf("pizza")),
    GoogleCompatEmoji("\ud83c\udf2d", listOf("hotdog")),
    GoogleCompatEmoji("\ud83e\udd6a", listOf("sandwich")),
    GoogleCompatEmoji("\ud83c\udf2e", listOf("taco")),
    GoogleCompatEmoji("\ud83c\udf2f", listOf("burrito")),
    GoogleCompatEmoji("\ud83e\uded4", listOf("tamale")),
    GoogleCompatEmoji("\ud83e\udd59", listOf("stuffed_flatbread")),
    GoogleCompatEmoji("\ud83e\uddc6", listOf("falafel")),
    GoogleCompatEmoji("\ud83e\udd5a", listOf("egg")),
    GoogleCompatEmoji("\ud83c\udf73", listOf("fried_egg", "cooking")),
    GoogleCompatEmoji("\ud83e\udd58", listOf("shallow_pan_of_food")),
    GoogleCompatEmoji("\ud83c\udf72", listOf("stew")),
    GoogleCompatEmoji("\ud83e\uded5", listOf("fondue")),
    GoogleCompatEmoji("\ud83e\udd63", listOf("bowl_with_spoon")),
    GoogleCompatEmoji("\ud83e\udd57", listOf("green_salad")),
    GoogleCompatEmoji("\ud83c\udf7f", listOf("popcorn")),
    GoogleCompatEmoji("\ud83e\uddc8", listOf("butter")),
    GoogleCompatEmoji("\ud83e\uddc2", listOf("salt")),
    GoogleCompatEmoji("\ud83e\udd6b", listOf("canned_food")),
    GoogleCompatEmoji("\ud83c\udf71", listOf("bento")),
    GoogleCompatEmoji("\ud83c\udf58", listOf("rice_cracker")),
    GoogleCompatEmoji("\ud83c\udf59", listOf("rice_ball")),
    GoogleCompatEmoji("\ud83c\udf5a", listOf("rice")),
    GoogleCompatEmoji("\ud83c\udf5b", listOf("curry")),
    GoogleCompatEmoji("\ud83c\udf5c", listOf("ramen")),
    GoogleCompatEmoji("\ud83c\udf5d", listOf("spaghetti")),
    GoogleCompatEmoji("\ud83c\udf60", listOf("sweet_potato")),
    GoogleCompatEmoji("\ud83c\udf62", listOf("oden")),
    GoogleCompatEmoji("\ud83c\udf63", listOf("sushi")),
    GoogleCompatEmoji("\ud83c\udf64", listOf("fried_shrimp")),
    GoogleCompatEmoji("\ud83c\udf65", listOf("fish_cake")),
    GoogleCompatEmoji("\ud83e\udd6e", listOf("moon_cake")),
    GoogleCompatEmoji("\ud83c\udf61", listOf("dango")),
    GoogleCompatEmoji("\ud83e\udd5f", listOf("dumpling")),
    GoogleCompatEmoji("\ud83e\udd60", listOf("fortune_cookie")),
    GoogleCompatEmoji("\ud83e\udd61", listOf("takeout_box")),
    GoogleCompatEmoji("\ud83e\udd80", listOf("crab")),
    GoogleCompatEmoji("\ud83e\udd9e", listOf("lobster")),
    GoogleCompatEmoji("\ud83e\udd90", listOf("shrimp")),
    GoogleCompatEmoji("\ud83e\udd91", listOf("squid")),
    GoogleCompatEmoji("\ud83e\uddaa", listOf("oyster")),
    GoogleCompatEmoji("\ud83c\udf66", listOf("icecream")),
    GoogleCompatEmoji("\ud83c\udf67", listOf("shaved_ice")),
    GoogleCompatEmoji("\ud83c\udf68", listOf("ice_cream")),
    GoogleCompatEmoji("\ud83c\udf69", listOf("doughnut")),
    GoogleCompatEmoji("\ud83c\udf6a", listOf("cookie")),
    GoogleCompatEmoji("\ud83c\udf82", listOf("birthday")),
  )
}
