/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk1 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x1F4D2), 0, 1), listOf("ledger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C3), 0, 1), listOf("page_with_curl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4DC), 0, 1), listOf("scroll"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C4), 0, 1), listOf("page_facing_up"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4F0), 0, 1), listOf("newspaper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5DE, 0xFE0F), 0, 2), listOf("rolled_up_newspaper"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4D1), 0, 1), listOf("bookmark_tabs"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F516), 0, 1), listOf("bookmark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F7, 0xFE0F), 0, 2), listOf("label"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B0), 0, 1), listOf("moneybag"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA99), 0, 1), listOf("coin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B4), 0, 1), listOf("yen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B5), 0, 1), listOf("dollar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B6), 0, 1), listOf("euro"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B7), 0, 1), listOf("pound"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B8), 0, 1), listOf("money_with_wings"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B3), 0, 1), listOf("credit_card"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9FE), 0, 1), listOf("receipt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4B9), 0, 1), listOf("chart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2709, 0xFE0F), 0, 2), listOf("email", "envelope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E7), 0, 1), listOf("e-mail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E8), 0, 1), listOf("incoming_envelope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E9), 0, 1), listOf("envelope_with_arrow"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E4), 0, 1), listOf("outbox_tray"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E5), 0, 1), listOf("inbox_tray"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E6), 0, 1), listOf("package"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4EB), 0, 1), listOf("mailbox"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4EA), 0, 1), listOf("mailbox_closed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4EC), 0, 1), listOf("mailbox_with_mail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4ED), 0, 1), listOf("mailbox_with_no_mail"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4EE), 0, 1), listOf("postbox"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5F3, 0xFE0F), 0, 2), listOf("ballot_box_with_ballot"), false),
    GoogleCompatEmoji(String(intArrayOf(0x270F, 0xFE0F), 0, 2), listOf("pencil2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2712, 0xFE0F), 0, 2), listOf("black_nib"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58B, 0xFE0F), 0, 2), listOf("lower_left_fountain_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58A, 0xFE0F), 0, 2), listOf("lower_left_ballpoint_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58C, 0xFE0F), 0, 2), listOf("lower_left_paintbrush"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F58D, 0xFE0F), 0, 2), listOf("lower_left_crayon"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4DD), 0, 1), listOf("memo", "pencil"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4BC), 0, 1), listOf("briefcase"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C1), 0, 1), listOf("file_folder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C2), 0, 1), listOf("open_file_folder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C2, 0xFE0F), 0, 2), listOf("card_index_dividers"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C5), 0, 1), listOf("date"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C6), 0, 1), listOf("calendar"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D2, 0xFE0F), 0, 2), listOf("spiral_note_pad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D3, 0xFE0F), 0, 2), listOf("spiral_calendar_pad"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C7), 0, 1), listOf("card_index"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C8), 0, 1), listOf("chart_with_upwards_trend"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4C9), 0, 1), listOf("chart_with_downwards_trend"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CA), 0, 1), listOf("bar_chart"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CB), 0, 1), listOf("clipboard"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CC), 0, 1), listOf("pushpin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CD), 0, 1), listOf("round_pushpin"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CE), 0, 1), listOf("paperclip"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F587, 0xFE0F), 0, 2), listOf("linked_paperclips"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4CF), 0, 1), listOf("straight_ruler"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4D0), 0, 1), listOf("triangular_ruler"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2702, 0xFE0F), 0, 2), listOf("scissors"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C3, 0xFE0F), 0, 2), listOf("card_file_box"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5C4, 0xFE0F), 0, 2), listOf("file_cabinet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5D1, 0xFE0F), 0, 2), listOf("wastebasket"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F512), 0, 1), listOf("lock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F513), 0, 1), listOf("unlock"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F50F), 0, 1), listOf("lock_with_ink_pen"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F510), 0, 1), listOf("closed_lock_with_key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F511), 0, 1), listOf("key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5DD, 0xFE0F), 0, 2), listOf("old_key"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F528), 0, 1), listOf("hammer"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA93), 0, 1), listOf("axe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26CF, 0xFE0F), 0, 2), listOf("pick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2692, 0xFE0F), 0, 2), listOf("hammer_and_pick"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E0, 0xFE0F), 0, 2), listOf("hammer_and_wrench"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5E1, 0xFE0F), 0, 2), listOf("dagger_knife"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2694, 0xFE0F), 0, 2), listOf("crossed_swords"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4A3), 0, 1), listOf("bomb"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA83), 0, 1), listOf("boomerang"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F3F9), 0, 1), listOf("bow_and_arrow"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6E1, 0xFE0F), 0, 2), listOf("shield"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9A), 0, 1), listOf("carpentry_saw"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F527), 0, 1), listOf("wrench"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9B), 0, 1), listOf("screwdriver"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F529), 0, 1), listOf("nut_and_bolt"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2699, 0xFE0F), 0, 2), listOf("gear"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F5DC, 0xFE0F), 0, 2), listOf("compression"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2696, 0xFE0F), 0, 2), listOf("scales"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9AF), 0, 1), listOf("probing_cane"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F517), 0, 1), listOf("link"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26D3, 0xFE0F, 0x200D, 0x1F4A5), 0, 4), listOf("broken_chain"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26D3, 0xFE0F), 0, 2), listOf("chains"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9D), 0, 1), listOf("hook"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F0), 0, 1), listOf("toolbox"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9F2), 0, 1), listOf("magnet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9C), 0, 1), listOf("ladder"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2697, 0xFE0F), 0, 2), listOf("alembic"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EA), 0, 1), listOf("test_tube"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EB), 0, 1), listOf("petri_dish"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F9EC), 0, 1), listOf("dna"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52C), 0, 1), listOf("microscope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F52D), 0, 1), listOf("telescope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4E1), 0, 1), listOf("satellite_antenna"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F489), 0, 1), listOf("syringe"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA78), 0, 1), listOf("drop_of_blood"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F48A), 0, 1), listOf("pill"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA79), 0, 1), listOf("adhesive_bandage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7C), 0, 1), listOf("crutch"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7A), 0, 1), listOf("stethoscope"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA7B), 0, 1), listOf("x-ray"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6AA), 0, 1), listOf("door"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6D7), 0, 1), listOf("elevator"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9E), 0, 1), listOf("mirror"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA9F), 0, 1), listOf("window"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6CF, 0xFE0F), 0, 2), listOf("bed"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6CB, 0xFE0F), 0, 2), listOf("couch_and_lamp"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FA91), 0, 1), listOf("chair"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BD), 0, 1), listOf("toilet"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA0), 0, 1), listOf("plunger"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6BF), 0, 1), listOf("shower"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F6C1), 0, 1), listOf("bathtub"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1FAA4), 0, 1), listOf("mouse_trap"), false),
  )
}
