/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object ObjectsCategoryChunk1 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji("\ud83c\udfac", listOf("clapper")),
    GoogleCompatEmoji("\ud83d\udcfa", listOf("tv")),
    GoogleCompatEmoji("\ud83d\udcf7", listOf("camera")),
    GoogleCompatEmoji("\ud83d\udcf8", listOf("camera_with_flash")),
    GoogleCompatEmoji("\ud83d\udcf9", listOf("video_camera")),
    GoogleCompatEmoji("\ud83d\udcfc", listOf("vhs")),
    GoogleCompatEmoji("\ud83d\udd0d", listOf("mag")),
    GoogleCompatEmoji("\ud83d\udd0e", listOf("mag_right")),
    GoogleCompatEmoji("\ud83d\udd6f\ufe0f", listOf("candle")),
    GoogleCompatEmoji("\ud83d\udca1", listOf("bulb")),
    GoogleCompatEmoji("\ud83d\udd26", listOf("flashlight")),
    GoogleCompatEmoji("\ud83c\udfee", listOf("izakaya_lantern", "lantern")),
    GoogleCompatEmoji("\ud83e\ude94", listOf("diya_lamp")),
    GoogleCompatEmoji("\ud83d\udcd4", listOf("notebook_with_decorative_cover")),
    GoogleCompatEmoji("\ud83d\udcd5", listOf("closed_book")),
    GoogleCompatEmoji("\ud83d\udcd6", listOf("book", "open_book")),
    GoogleCompatEmoji("\ud83d\udcd7", listOf("green_book")),
    GoogleCompatEmoji("\ud83d\udcd8", listOf("blue_book")),
    GoogleCompatEmoji("\ud83d\udcd9", listOf("orange_book")),
    GoogleCompatEmoji("\ud83d\udcda", listOf("books")),
    GoogleCompatEmoji("\ud83d\udcd3", listOf("notebook")),
    GoogleCompatEmoji("\ud83d\udcd2", listOf("ledger")),
    GoogleCompatEmoji("\ud83d\udcc3", listOf("page_with_curl")),
    GoogleCompatEmoji("\ud83d\udcdc", listOf("scroll")),
    GoogleCompatEmoji("\ud83d\udcc4", listOf("page_facing_up")),
    GoogleCompatEmoji("\ud83d\udcf0", listOf("newspaper")),
    GoogleCompatEmoji("\ud83d\uddde\ufe0f", listOf("rolled_up_newspaper")),
    GoogleCompatEmoji("\ud83d\udcd1", listOf("bookmark_tabs")),
    GoogleCompatEmoji("\ud83d\udd16", listOf("bookmark")),
    GoogleCompatEmoji("\ud83c\udff7\ufe0f", listOf("label")),
    GoogleCompatEmoji("\ud83d\udcb0", listOf("moneybag")),
    GoogleCompatEmoji("\ud83e\ude99", listOf("coin")),
    GoogleCompatEmoji("\ud83d\udcb4", listOf("yen")),
    GoogleCompatEmoji("\ud83d\udcb5", listOf("dollar")),
    GoogleCompatEmoji("\ud83d\udcb6", listOf("euro")),
    GoogleCompatEmoji("\ud83d\udcb7", listOf("pound")),
    GoogleCompatEmoji("\ud83d\udcb8", listOf("money_with_wings")),
    GoogleCompatEmoji("\ud83d\udcb3", listOf("credit_card")),
    GoogleCompatEmoji("\ud83e\uddfe", listOf("receipt")),
    GoogleCompatEmoji("\ud83d\udcb9", listOf("chart")),
    GoogleCompatEmoji("\u2709\ufe0f", listOf("email", "envelope")),
    GoogleCompatEmoji("\ud83d\udce7", listOf("e-mail")),
    GoogleCompatEmoji("\ud83d\udce8", listOf("incoming_envelope")),
    GoogleCompatEmoji("\ud83d\udce9", listOf("envelope_with_arrow")),
    GoogleCompatEmoji("\ud83d\udce4", listOf("outbox_tray")),
    GoogleCompatEmoji("\ud83d\udce5", listOf("inbox_tray")),
    GoogleCompatEmoji("\ud83d\udce6", listOf("package")),
    GoogleCompatEmoji("\ud83d\udceb", listOf("mailbox")),
    GoogleCompatEmoji("\ud83d\udcea", listOf("mailbox_closed")),
    GoogleCompatEmoji("\ud83d\udcec", listOf("mailbox_with_mail")),
    GoogleCompatEmoji("\ud83d\udced", listOf("mailbox_with_no_mail")),
    GoogleCompatEmoji("\ud83d\udcee", listOf("postbox")),
    GoogleCompatEmoji("\ud83d\uddf3\ufe0f", listOf("ballot_box_with_ballot")),
    GoogleCompatEmoji("\u270f\ufe0f", listOf("pencil2")),
    GoogleCompatEmoji("\u2712\ufe0f", listOf("black_nib")),
    GoogleCompatEmoji("\ud83d\udd8b\ufe0f", listOf("lower_left_fountain_pen")),
    GoogleCompatEmoji("\ud83d\udd8a\ufe0f", listOf("lower_left_ballpoint_pen")),
    GoogleCompatEmoji("\ud83d\udd8c\ufe0f", listOf("lower_left_paintbrush")),
    GoogleCompatEmoji("\ud83d\udd8d\ufe0f", listOf("lower_left_crayon")),
    GoogleCompatEmoji("\ud83d\udcdd", listOf("memo", "pencil")),
    GoogleCompatEmoji("\ud83d\udcbc", listOf("briefcase")),
    GoogleCompatEmoji("\ud83d\udcc1", listOf("file_folder")),
    GoogleCompatEmoji("\ud83d\udcc2", listOf("open_file_folder")),
    GoogleCompatEmoji("\ud83d\uddc2\ufe0f", listOf("card_index_dividers")),
    GoogleCompatEmoji("\ud83d\udcc5", listOf("date")),
    GoogleCompatEmoji("\ud83d\udcc6", listOf("calendar")),
    GoogleCompatEmoji("\ud83d\uddd2\ufe0f", listOf("spiral_note_pad")),
    GoogleCompatEmoji("\ud83d\uddd3\ufe0f", listOf("spiral_calendar_pad")),
    GoogleCompatEmoji("\ud83d\udcc7", listOf("card_index")),
    GoogleCompatEmoji("\ud83d\udcc8", listOf("chart_with_upwards_trend")),
    GoogleCompatEmoji("\ud83d\udcc9", listOf("chart_with_downwards_trend")),
    GoogleCompatEmoji("\ud83d\udcca", listOf("bar_chart")),
    GoogleCompatEmoji("\ud83d\udccb", listOf("clipboard")),
    GoogleCompatEmoji("\ud83d\udccc", listOf("pushpin")),
    GoogleCompatEmoji("\ud83d\udccd", listOf("round_pushpin")),
    GoogleCompatEmoji("\ud83d\udcce", listOf("paperclip")),
    GoogleCompatEmoji("\ud83d\udd87\ufe0f", listOf("linked_paperclips")),
    GoogleCompatEmoji("\ud83d\udccf", listOf("straight_ruler")),
    GoogleCompatEmoji("\ud83d\udcd0", listOf("triangular_ruler")),
    GoogleCompatEmoji("\u2702\ufe0f", listOf("scissors")),
    GoogleCompatEmoji("\ud83d\uddc3\ufe0f", listOf("card_file_box")),
    GoogleCompatEmoji("\ud83d\uddc4\ufe0f", listOf("file_cabinet")),
    GoogleCompatEmoji("\ud83d\uddd1\ufe0f", listOf("wastebasket")),
    GoogleCompatEmoji("\ud83d\udd12", listOf("lock")),
    GoogleCompatEmoji("\ud83d\udd13", listOf("unlock")),
    GoogleCompatEmoji("\ud83d\udd0f", listOf("lock_with_ink_pen")),
    GoogleCompatEmoji("\ud83d\udd10", listOf("closed_lock_with_key")),
    GoogleCompatEmoji("\ud83d\udd11", listOf("key")),
    GoogleCompatEmoji("\ud83d\udddd\ufe0f", listOf("old_key")),
    GoogleCompatEmoji("\ud83d\udd28", listOf("hammer")),
    GoogleCompatEmoji("\ud83e\ude93", listOf("axe")),
    GoogleCompatEmoji("\u26cf\ufe0f", listOf("pick")),
    GoogleCompatEmoji("\u2692\ufe0f", listOf("hammer_and_pick")),
    GoogleCompatEmoji("\ud83d\udee0\ufe0f", listOf("hammer_and_wrench")),
    GoogleCompatEmoji("\ud83d\udde1\ufe0f", listOf("dagger_knife")),
    GoogleCompatEmoji("\u2694\ufe0f", listOf("crossed_swords")),
    GoogleCompatEmoji("\ud83d\udca3", listOf("bomb")),
    GoogleCompatEmoji("\ud83e\ude83", listOf("boomerang")),
    GoogleCompatEmoji("\ud83c\udff9", listOf("bow_and_arrow")),
    GoogleCompatEmoji("\ud83d\udee1\ufe0f", listOf("shield")),
  )
}
