/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SymbolsCategoryChunk1 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji(String(intArrayOf(0x2B55), 0, 1), listOf("o"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2705), 0, 1), listOf("white_check_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2611, 0xFE0F), 0, 2), listOf("ballot_box_with_check"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2714, 0xFE0F), 0, 2), listOf("heavy_check_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x274C), 0, 1), listOf("x"), false),
    GoogleCompatEmoji(String(intArrayOf(0x274E), 0, 1), listOf("negative_squared_cross_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x27B0), 0, 1), listOf("curly_loop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x27BF), 0, 1), listOf("loop"), false),
    GoogleCompatEmoji(String(intArrayOf(0x303D, 0xFE0F), 0, 2), listOf("part_alternation_mark"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2733, 0xFE0F), 0, 2), listOf("eight_spoked_asterisk"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2734, 0xFE0F), 0, 2), listOf("eight_pointed_black_star"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2747, 0xFE0F), 0, 2), listOf("sparkle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x00A9, 0xFE0F), 0, 2), listOf("copyright"), false),
    GoogleCompatEmoji(String(intArrayOf(0x00AE, 0xFE0F), 0, 2), listOf("registered"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2122, 0xFE0F), 0, 2), listOf("tm"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0023, 0xFE0F, 0x20E3), 0, 3), listOf("hash"), false),
    GoogleCompatEmoji(String(intArrayOf(0x002A, 0xFE0F, 0x20E3), 0, 3), listOf("keycap_star"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0030, 0xFE0F, 0x20E3), 0, 3), listOf("zero"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0031, 0xFE0F, 0x20E3), 0, 3), listOf("one"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0032, 0xFE0F, 0x20E3), 0, 3), listOf("two"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0033, 0xFE0F, 0x20E3), 0, 3), listOf("three"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0034, 0xFE0F, 0x20E3), 0, 3), listOf("four"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0035, 0xFE0F, 0x20E3), 0, 3), listOf("five"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0036, 0xFE0F, 0x20E3), 0, 3), listOf("six"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0037, 0xFE0F, 0x20E3), 0, 3), listOf("seven"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0038, 0xFE0F, 0x20E3), 0, 3), listOf("eight"), false),
    GoogleCompatEmoji(String(intArrayOf(0x0039, 0xFE0F, 0x20E3), 0, 3), listOf("nine"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F51F), 0, 1), listOf("keycap_ten"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F520), 0, 1), listOf("capital_abcd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F521), 0, 1), listOf("abcd"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F522), 0, 1), listOf("1234"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F523), 0, 1), listOf("symbols"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F524), 0, 1), listOf("abc"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F170, 0xFE0F), 0, 2), listOf("a"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F18E), 0, 1), listOf("ab"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F171, 0xFE0F), 0, 2), listOf("b"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F191), 0, 1), listOf("cl"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F192), 0, 1), listOf("cool"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F193), 0, 1), listOf("free"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2139, 0xFE0F), 0, 2), listOf("information_source"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F194), 0, 1), listOf("id"), false),
    GoogleCompatEmoji(String(intArrayOf(0x24C2, 0xFE0F), 0, 2), listOf("m"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F195), 0, 1), listOf("new"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F196), 0, 1), listOf("ng"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F17E, 0xFE0F), 0, 2), listOf("o2"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F197), 0, 1), listOf("ok"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F17F, 0xFE0F), 0, 2), listOf("parking"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F198), 0, 1), listOf("sos"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F199), 0, 1), listOf("up"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F19A), 0, 1), listOf("vs"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F201), 0, 1), listOf("koko"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F202, 0xFE0F), 0, 2), listOf("sa"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F237, 0xFE0F), 0, 2), listOf("u6708"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F236), 0, 1), listOf("u6709"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F22F), 0, 1), listOf("u6307"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F250), 0, 1), listOf("ideograph_advantage"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F239), 0, 1), listOf("u5272"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F21A), 0, 1), listOf("u7121"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F232), 0, 1), listOf("u7981"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F251), 0, 1), listOf("accept"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F238), 0, 1), listOf("u7533"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F234), 0, 1), listOf("u5408"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F233), 0, 1), listOf("u7a7a"), false),
    GoogleCompatEmoji(String(intArrayOf(0x3297, 0xFE0F), 0, 2), listOf("congratulations"), false),
    GoogleCompatEmoji(String(intArrayOf(0x3299, 0xFE0F), 0, 2), listOf("secret"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F23A), 0, 1), listOf("u55b6"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F235), 0, 1), listOf("u6e80"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F534), 0, 1), listOf("red_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E0), 0, 1), listOf("large_orange_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E1), 0, 1), listOf("large_yellow_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E2), 0, 1), listOf("large_green_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F535), 0, 1), listOf("large_blue_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E3), 0, 1), listOf("large_purple_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E4), 0, 1), listOf("large_brown_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26AB), 0, 1), listOf("black_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x26AA), 0, 1), listOf("white_circle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E5), 0, 1), listOf("large_red_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E7), 0, 1), listOf("large_orange_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E8), 0, 1), listOf("large_yellow_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E9), 0, 1), listOf("large_green_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7E6), 0, 1), listOf("large_blue_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7EA), 0, 1), listOf("large_purple_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F7EB), 0, 1), listOf("large_brown_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B1B), 0, 1), listOf("black_large_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x2B1C), 0, 1), listOf("white_large_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25FC, 0xFE0F), 0, 2), listOf("black_medium_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25FB, 0xFE0F), 0, 2), listOf("white_medium_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25FE), 0, 1), listOf("black_medium_small_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25FD), 0, 1), listOf("white_medium_small_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25AA, 0xFE0F), 0, 2), listOf("black_small_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x25AB, 0xFE0F), 0, 2), listOf("white_small_square"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F536), 0, 1), listOf("large_orange_diamond"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F537), 0, 1), listOf("large_blue_diamond"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F538), 0, 1), listOf("small_orange_diamond"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F539), 0, 1), listOf("small_blue_diamond"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F53A), 0, 1), listOf("small_red_triangle"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F53B), 0, 1), listOf("small_red_triangle_down"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F4A0), 0, 1), listOf("diamond_shape_with_a_dot_inside"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F518), 0, 1), listOf("radio_button"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F533), 0, 1), listOf("white_square_button"), false),
    GoogleCompatEmoji(String(intArrayOf(0x1F532), 0, 1), listOf("black_square_button"), false),
  )
}
