/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object SymbolsCategoryChunk0 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji("\ud83c\udfe7", listOf("atm")),
    GoogleCompatEmoji("\ud83d\udeae", listOf("put_litter_in_its_place")),
    GoogleCompatEmoji("\ud83d\udeb0", listOf("potable_water")),
    GoogleCompatEmoji("\u267f", listOf("wheelchair")),
    GoogleCompatEmoji("\ud83d\udeb9", listOf("mens")),
    GoogleCompatEmoji("\ud83d\udeba", listOf("womens")),
    GoogleCompatEmoji("\ud83d\udebb", listOf("restroom")),
    GoogleCompatEmoji("\ud83d\udebc", listOf("baby_symbol")),
    GoogleCompatEmoji("\ud83d\udebe", listOf("wc")),
    GoogleCompatEmoji("\ud83d\udec2", listOf("passport_control")),
    GoogleCompatEmoji("\ud83d\udec3", listOf("customs")),
    GoogleCompatEmoji("\ud83d\udec4", listOf("baggage_claim")),
    GoogleCompatEmoji("\ud83d\udec5", listOf("left_luggage")),
    GoogleCompatEmoji("\u26a0\ufe0f", listOf("warning")),
    GoogleCompatEmoji("\ud83d\udeb8", listOf("children_crossing")),
    GoogleCompatEmoji("\u26d4", listOf("no_entry")),
    GoogleCompatEmoji("\ud83d\udeab", listOf("no_entry_sign")),
    GoogleCompatEmoji("\ud83d\udeb3", listOf("no_bicycles")),
    GoogleCompatEmoji("\ud83d\udead", listOf("no_smoking")),
    GoogleCompatEmoji("\ud83d\udeaf", listOf("do_not_litter")),
    GoogleCompatEmoji("\ud83d\udeb1", listOf("non-potable_water")),
    GoogleCompatEmoji("\ud83d\udeb7", listOf("no_pedestrians")),
    GoogleCompatEmoji("\ud83d\udcf5", listOf("no_mobile_phones")),
    GoogleCompatEmoji("\ud83d\udd1e", listOf("underage")),
    GoogleCompatEmoji("\u2622\ufe0f", listOf("radioactive_sign")),
    GoogleCompatEmoji("\u2623\ufe0f", listOf("biohazard_sign")),
    GoogleCompatEmoji("\u2b06\ufe0f", listOf("arrow_up")),
    GoogleCompatEmoji("\u2197\ufe0f", listOf("arrow_upper_right")),
    GoogleCompatEmoji("\u27a1\ufe0f", listOf("arrow_right")),
    GoogleCompatEmoji("\u2198\ufe0f", listOf("arrow_lower_right")),
    GoogleCompatEmoji("\u2b07\ufe0f", listOf("arrow_down")),
    GoogleCompatEmoji("\u2199\ufe0f", listOf("arrow_lower_left")),
    GoogleCompatEmoji("\u2b05\ufe0f", listOf("arrow_left")),
    GoogleCompatEmoji("\u2196\ufe0f", listOf("arrow_upper_left")),
    GoogleCompatEmoji("\u2195\ufe0f", listOf("arrow_up_down")),
    GoogleCompatEmoji("\u2194\ufe0f", listOf("left_right_arrow")),
    GoogleCompatEmoji("\u21a9\ufe0f", listOf("leftwards_arrow_with_hook")),
    GoogleCompatEmoji("\u21aa\ufe0f", listOf("arrow_right_hook")),
    GoogleCompatEmoji("\u2934\ufe0f", listOf("arrow_heading_up")),
    GoogleCompatEmoji("\u2935\ufe0f", listOf("arrow_heading_down")),
    GoogleCompatEmoji("\ud83d\udd03", listOf("arrows_clockwise")),
    GoogleCompatEmoji("\ud83d\udd04", listOf("arrows_counterclockwise")),
    GoogleCompatEmoji("\ud83d\udd19", listOf("back")),
    GoogleCompatEmoji("\ud83d\udd1a", listOf("end")),
    GoogleCompatEmoji("\ud83d\udd1b", listOf("on")),
    GoogleCompatEmoji("\ud83d\udd1c", listOf("soon")),
    GoogleCompatEmoji("\ud83d\udd1d", listOf("top")),
    GoogleCompatEmoji("\ud83d\uded0", listOf("place_of_worship")),
    GoogleCompatEmoji("\u269b\ufe0f", listOf("atom_symbol")),
    GoogleCompatEmoji("\ud83d\udd49\ufe0f", listOf("om_symbol")),
    GoogleCompatEmoji("\u2721\ufe0f", listOf("star_of_david")),
    GoogleCompatEmoji("\u2638\ufe0f", listOf("wheel_of_dharma")),
    GoogleCompatEmoji("\u262f\ufe0f", listOf("yin_yang")),
    GoogleCompatEmoji("\u271d\ufe0f", listOf("latin_cross")),
    GoogleCompatEmoji("\u2626\ufe0f", listOf("orthodox_cross")),
    GoogleCompatEmoji("\u262a\ufe0f", listOf("star_and_crescent")),
    GoogleCompatEmoji("\u262e\ufe0f", listOf("peace_symbol")),
    GoogleCompatEmoji("\ud83d\udd4e", listOf("menorah_with_nine_branches")),
    GoogleCompatEmoji("\ud83d\udd2f", listOf("six_pointed_star")),
    GoogleCompatEmoji("\ud83e\udeaf", listOf("khanda")),
    GoogleCompatEmoji("\u2648", listOf("aries")),
    GoogleCompatEmoji("\u2649", listOf("taurus")),
    GoogleCompatEmoji("\u264a", listOf("gemini")),
    GoogleCompatEmoji("\u264b", listOf("cancer")),
    GoogleCompatEmoji("\u264c", listOf("leo")),
    GoogleCompatEmoji("\u264d", listOf("virgo")),
    GoogleCompatEmoji("\u264e", listOf("libra")),
    GoogleCompatEmoji("\u264f", listOf("scorpius")),
    GoogleCompatEmoji("\u2650", listOf("sagittarius")),
    GoogleCompatEmoji("\u2651", listOf("capricorn")),
    GoogleCompatEmoji("\u2652", listOf("aquarius")),
    GoogleCompatEmoji("\u2653", listOf("pisces")),
    GoogleCompatEmoji("\u26ce", listOf("ophiuchus")),
    GoogleCompatEmoji("\ud83d\udd00", listOf("twisted_rightwards_arrows")),
    GoogleCompatEmoji("\ud83d\udd01", listOf("repeat")),
    GoogleCompatEmoji("\ud83d\udd02", listOf("repeat_one")),
    GoogleCompatEmoji("\u25b6\ufe0f", listOf("arrow_forward")),
    GoogleCompatEmoji("\u23e9", listOf("fast_forward")),
    GoogleCompatEmoji("\u23ed\ufe0f", listOf("black_right_pointing_double_triangle_with_vertical_bar")),
    GoogleCompatEmoji("\u23ef\ufe0f", listOf("black_right_pointing_triangle_with_double_vertical_bar")),
    GoogleCompatEmoji("\u25c0\ufe0f", listOf("arrow_backward")),
    GoogleCompatEmoji("\u23ea", listOf("rewind")),
    GoogleCompatEmoji("\u23ee\ufe0f", listOf("black_left_pointing_double_triangle_with_vertical_bar")),
    GoogleCompatEmoji("\ud83d\udd3c", listOf("arrow_up_small")),
    GoogleCompatEmoji("\u23eb", listOf("arrow_double_up")),
    GoogleCompatEmoji("\ud83d\udd3d", listOf("arrow_down_small")),
    GoogleCompatEmoji("\u23ec", listOf("arrow_double_down")),
    GoogleCompatEmoji("\u23f8\ufe0f", listOf("double_vertical_bar")),
    GoogleCompatEmoji("\u23f9\ufe0f", listOf("black_square_for_stop")),
    GoogleCompatEmoji("\u23fa\ufe0f", listOf("black_circle_for_record")),
    GoogleCompatEmoji("\u23cf\ufe0f", listOf("eject")),
    GoogleCompatEmoji("\ud83c\udfa6", listOf("cinema")),
    GoogleCompatEmoji("\ud83d\udd05", listOf("low_brightness")),
    GoogleCompatEmoji("\ud83d\udd06", listOf("high_brightness")),
    GoogleCompatEmoji("\ud83d\udcf6", listOf("signal_strength")),
    GoogleCompatEmoji("\ud83d\udedc", listOf("wireless")),
    GoogleCompatEmoji("\ud83d\udcf3", listOf("vibration_mode")),
    GoogleCompatEmoji("\ud83d\udcf4", listOf("mobile_phone_off")),
    GoogleCompatEmoji("\u2640\ufe0f", listOf("female_sign")),
    GoogleCompatEmoji("\u2642\ufe0f", listOf("male_sign")),
  )
}
