/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.googlecompat.category

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji

internal object TravelAndPlacesCategoryChunk1 {
  internal val EMOJIS: List<GoogleCompatEmoji> = listOf(
    GoogleCompatEmoji("\ud83d\udefa", listOf("auto_rickshaw")),
    GoogleCompatEmoji("\ud83d\udeb2", listOf("bike")),
    GoogleCompatEmoji("\ud83d\udef4", listOf("scooter")),
    GoogleCompatEmoji("\ud83d\udef9", listOf("skateboard")),
    GoogleCompatEmoji("\ud83d\udefc", listOf("roller_skate")),
    GoogleCompatEmoji("\ud83d\ude8f", listOf("busstop")),
    GoogleCompatEmoji("\ud83d\udee3\ufe0f", listOf("motorway")),
    GoogleCompatEmoji("\ud83d\udee4\ufe0f", listOf("railway_track")),
    GoogleCompatEmoji("\ud83d\udee2\ufe0f", listOf("oil_drum")),
    GoogleCompatEmoji("\u26fd", listOf("fuelpump")),
    GoogleCompatEmoji("\ud83d\udede", listOf("wheel")),
    GoogleCompatEmoji("\ud83d\udea8", listOf("rotating_light")),
    GoogleCompatEmoji("\ud83d\udea5", listOf("traffic_light")),
    GoogleCompatEmoji("\ud83d\udea6", listOf("vertical_traffic_light")),
    GoogleCompatEmoji("\ud83d\uded1", listOf("octagonal_sign")),
    GoogleCompatEmoji("\ud83d\udea7", listOf("construction")),
    GoogleCompatEmoji("\u2693", listOf("anchor")),
    GoogleCompatEmoji("\ud83d\udedf", listOf("ring_buoy")),
    GoogleCompatEmoji("\u26f5", listOf("boat", "sailboat")),
    GoogleCompatEmoji("\ud83d\udef6", listOf("canoe")),
    GoogleCompatEmoji("\ud83d\udea4", listOf("speedboat")),
    GoogleCompatEmoji("\ud83d\udef3\ufe0f", listOf("passenger_ship")),
    GoogleCompatEmoji("\u26f4\ufe0f", listOf("ferry")),
    GoogleCompatEmoji("\ud83d\udee5\ufe0f", listOf("motor_boat")),
    GoogleCompatEmoji("\ud83d\udea2", listOf("ship")),
    GoogleCompatEmoji("\u2708\ufe0f", listOf("airplane")),
    GoogleCompatEmoji("\ud83d\udee9\ufe0f", listOf("small_airplane")),
    GoogleCompatEmoji("\ud83d\udeeb", listOf("airplane_departure")),
    GoogleCompatEmoji("\ud83d\udeec", listOf("airplane_arriving")),
    GoogleCompatEmoji("\ud83e\ude82", listOf("parachute")),
    GoogleCompatEmoji("\ud83d\udcba", listOf("seat")),
    GoogleCompatEmoji("\ud83d\ude81", listOf("helicopter")),
    GoogleCompatEmoji("\ud83d\ude9f", listOf("suspension_railway")),
    GoogleCompatEmoji("\ud83d\udea0", listOf("mountain_cableway")),
    GoogleCompatEmoji("\ud83d\udea1", listOf("aerial_tramway")),
    GoogleCompatEmoji("\ud83d\udef0\ufe0f", listOf("satellite")),
    GoogleCompatEmoji("\ud83d\ude80", listOf("rocket")),
    GoogleCompatEmoji("\ud83d\udef8", listOf("flying_saucer")),
    GoogleCompatEmoji("\ud83d\udece\ufe0f", listOf("bellhop_bell")),
    GoogleCompatEmoji("\ud83e\uddf3", listOf("luggage")),
    GoogleCompatEmoji("\u231b", listOf("hourglass")),
    GoogleCompatEmoji("\u23f3", listOf("hourglass_flowing_sand")),
    GoogleCompatEmoji("\u231a", listOf("watch")),
    GoogleCompatEmoji("\u23f0", listOf("alarm_clock")),
    GoogleCompatEmoji("\u23f1\ufe0f", listOf("stopwatch")),
    GoogleCompatEmoji("\u23f2\ufe0f", listOf("timer_clock")),
    GoogleCompatEmoji("\ud83d\udd70\ufe0f", listOf("mantelpiece_clock")),
    GoogleCompatEmoji("\ud83d\udd5b", listOf("clock12")),
    GoogleCompatEmoji("\ud83d\udd67", listOf("clock1230")),
    GoogleCompatEmoji("\ud83d\udd50", listOf("clock1")),
    GoogleCompatEmoji("\ud83d\udd5c", listOf("clock130")),
    GoogleCompatEmoji("\ud83d\udd51", listOf("clock2")),
    GoogleCompatEmoji("\ud83d\udd5d", listOf("clock230")),
    GoogleCompatEmoji("\ud83d\udd52", listOf("clock3")),
    GoogleCompatEmoji("\ud83d\udd5e", listOf("clock330")),
    GoogleCompatEmoji("\ud83d\udd53", listOf("clock4")),
    GoogleCompatEmoji("\ud83d\udd5f", listOf("clock430")),
    GoogleCompatEmoji("\ud83d\udd54", listOf("clock5")),
    GoogleCompatEmoji("\ud83d\udd60", listOf("clock530")),
    GoogleCompatEmoji("\ud83d\udd55", listOf("clock6")),
    GoogleCompatEmoji("\ud83d\udd61", listOf("clock630")),
    GoogleCompatEmoji("\ud83d\udd56", listOf("clock7")),
    GoogleCompatEmoji("\ud83d\udd62", listOf("clock730")),
    GoogleCompatEmoji("\ud83d\udd57", listOf("clock8")),
    GoogleCompatEmoji("\ud83d\udd63", listOf("clock830")),
    GoogleCompatEmoji("\ud83d\udd58", listOf("clock9")),
    GoogleCompatEmoji("\ud83d\udd64", listOf("clock930")),
    GoogleCompatEmoji("\ud83d\udd59", listOf("clock10")),
    GoogleCompatEmoji("\ud83d\udd65", listOf("clock1030")),
    GoogleCompatEmoji("\ud83d\udd5a", listOf("clock11")),
    GoogleCompatEmoji("\ud83d\udd66", listOf("clock1130")),
    GoogleCompatEmoji("\ud83c\udf11", listOf("new_moon")),
    GoogleCompatEmoji("\ud83c\udf12", listOf("waxing_crescent_moon")),
    GoogleCompatEmoji("\ud83c\udf13", listOf("first_quarter_moon")),
    GoogleCompatEmoji("\ud83c\udf14", listOf("moon", "waxing_gibbous_moon")),
    GoogleCompatEmoji("\ud83c\udf15", listOf("full_moon")),
    GoogleCompatEmoji("\ud83c\udf16", listOf("waning_gibbous_moon")),
    GoogleCompatEmoji("\ud83c\udf17", listOf("last_quarter_moon")),
    GoogleCompatEmoji("\ud83c\udf18", listOf("waning_crescent_moon")),
    GoogleCompatEmoji("\ud83c\udf19", listOf("crescent_moon")),
    GoogleCompatEmoji("\ud83c\udf1a", listOf("new_moon_with_face")),
    GoogleCompatEmoji("\ud83c\udf1b", listOf("first_quarter_moon_with_face")),
    GoogleCompatEmoji("\ud83c\udf1c", listOf("last_quarter_moon_with_face")),
    GoogleCompatEmoji("\ud83c\udf21\ufe0f", listOf("thermometer")),
    GoogleCompatEmoji("\u2600\ufe0f", listOf("sunny")),
    GoogleCompatEmoji("\ud83c\udf1d", listOf("full_moon_with_face")),
    GoogleCompatEmoji("\ud83c\udf1e", listOf("sun_with_face")),
    GoogleCompatEmoji("\ud83e\ude90", listOf("ringed_planet")),
    GoogleCompatEmoji("\u2b50", listOf("star")),
    GoogleCompatEmoji("\ud83c\udf1f", listOf("star2")),
    GoogleCompatEmoji("\ud83c\udf20", listOf("stars")),
    GoogleCompatEmoji("\ud83c\udf0c", listOf("milky_way")),
    GoogleCompatEmoji("\u2601\ufe0f", listOf("cloud")),
    GoogleCompatEmoji("\u26c5", listOf("partly_sunny")),
    GoogleCompatEmoji("\u26c8\ufe0f", listOf("thunder_cloud_and_rain")),
    GoogleCompatEmoji("\ud83c\udf24\ufe0f", listOf("mostly_sunny", "sun_small_cloud")),
    GoogleCompatEmoji("\ud83c\udf25\ufe0f", listOf("barely_sunny", "sun_behind_cloud")),
    GoogleCompatEmoji("\ud83c\udf26\ufe0f", listOf("partly_sunny_rain", "sun_behind_rain_cloud")),
    GoogleCompatEmoji("\ud83c\udf27\ufe0f", listOf("rain_cloud")),
    GoogleCompatEmoji("\ud83c\udf28\ufe0f", listOf("snow_cloud")),
  )
}
