/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.ios.category

import com.vanniktech.emoji.ios.IosEmoji

internal object TravelAndPlacesCategoryChunk0 {
  internal val EMOJIS: List<IosEmoji> = listOf(
    IosEmoji("\ud83c\udf0d", listOf("earth_africa"), 5, 8),
    IosEmoji("\ud83c\udf0e", listOf("earth_americas"), 5, 9),
    IosEmoji("\ud83c\udf0f", listOf("earth_asia"), 5, 10),
    IosEmoji("\ud83c\udf10", listOf("globe_with_meridians"), 5, 11),
    IosEmoji("\ud83d\uddfa\ufe0f", listOf("world_map"), 32, 41),
    IosEmoji("\ud83d\uddfe", listOf("japan"), 32, 45),
    IosEmoji("\ud83e\udded", listOf("compass"), 54, 32),
    IosEmoji("\ud83c\udfd4\ufe0f", listOf("snow_capped_mountain"), 10, 10),
    IosEmoji("\u26f0\ufe0f", listOf("mountain"), 59, 32),
    IosEmoji("\ud83c\udf0b", listOf("volcano"), 5, 6),
    IosEmoji("\ud83d\uddfb", listOf("mount_fuji"), 32, 42),
    IosEmoji("\ud83c\udfd5\ufe0f", listOf("camping"), 10, 11),
    IosEmoji("\ud83c\udfd6\ufe0f", listOf("beach_with_umbrella"), 10, 12),
    IosEmoji("\ud83c\udfdc\ufe0f", listOf("desert"), 10, 18),
    IosEmoji("\ud83c\udfdd\ufe0f", listOf("desert_island"), 10, 19),
    IosEmoji("\ud83c\udfde\ufe0f", listOf("national_park"), 10, 20),
    IosEmoji("\ud83c\udfdf\ufe0f", listOf("stadium"), 10, 21),
    IosEmoji("\ud83c\udfdb\ufe0f", listOf("classical_building"), 10, 17),
    IosEmoji("\ud83c\udfd7\ufe0f", listOf("building_construction"), 10, 13),
    IosEmoji("\ud83e\uddf1", listOf("bricks"), 54, 36),
    IosEmoji("\ud83e\udea8", listOf("rock"), 55, 37),
    IosEmoji("\ud83e\udeb5", listOf("wood"), 55, 50),
    IosEmoji("\ud83d\uded6", listOf("hut"), 38, 47),
    IosEmoji("\ud83c\udfd8\ufe0f", listOf("house_buildings"), 10, 14),
    IosEmoji("\ud83c\udfda\ufe0f", listOf("derelict_house_building"), 10, 16),
    IosEmoji("\ud83c\udfe0", listOf("house"), 10, 22),
    IosEmoji("\ud83c\udfe1", listOf("house_with_garden"), 10, 23),
    IosEmoji("\ud83c\udfe2", listOf("office"), 10, 24),
    IosEmoji("\ud83c\udfe3", listOf("post_office"), 10, 25),
    IosEmoji("\ud83c\udfe4", listOf("european_post_office"), 10, 26),
    IosEmoji("\ud83c\udfe5", listOf("hospital"), 10, 27),
    IosEmoji("\ud83c\udfe6", listOf("bank"), 10, 28),
    IosEmoji("\ud83c\udfe8", listOf("hotel"), 10, 30),
    IosEmoji("\ud83c\udfe9", listOf("love_hotel"), 10, 31),
    IosEmoji("\ud83c\udfea", listOf("convenience_store"), 10, 32),
    IosEmoji("\ud83c\udfeb", listOf("school"), 10, 33),
    IosEmoji("\ud83c\udfec", listOf("department_store"), 10, 34),
    IosEmoji("\ud83c\udfed", listOf("factory"), 10, 35),
    IosEmoji("\ud83c\udfef", listOf("japanese_castle"), 10, 37),
    IosEmoji("\ud83c\udff0", listOf("european_castle"), 10, 38),
    IosEmoji("\ud83d\udc92", listOf("wedding"), 28, 3),
    IosEmoji("\ud83d\uddfc", listOf("tokyo_tower"), 32, 43),
    IosEmoji("\ud83d\uddfd", listOf("statue_of_liberty"), 32, 44),
    IosEmoji("\u26ea", listOf("church"), 59, 31),
    IosEmoji("\ud83d\udd4c", listOf("mosque"), 30, 58),
    IosEmoji("\ud83d\uded5", listOf("hindu_temple"), 38, 46),
    IosEmoji("\ud83d\udd4d", listOf("synagogue"), 30, 59),
    IosEmoji("\u26e9\ufe0f", listOf("shinto_shrine"), 59, 30),
    IosEmoji("\ud83d\udd4b", listOf("kaaba"), 30, 57),
    IosEmoji("\u26f2", listOf("fountain"), 59, 34),
    IosEmoji("\u26fa", listOf("tent"), 59, 58),
    IosEmoji("\ud83c\udf01", listOf("foggy"), 4, 58),
    IosEmoji("\ud83c\udf03", listOf("night_with_stars"), 4, 60),
    IosEmoji("\ud83c\udfd9\ufe0f", listOf("cityscape"), 10, 15),
    IosEmoji("\ud83c\udf04", listOf("sunrise_over_mountains"), 4, 61),
    IosEmoji("\ud83c\udf05", listOf("sunrise"), 5, 0),
    IosEmoji("\ud83c\udf06", listOf("city_sunset"), 5, 1),
    IosEmoji("\ud83c\udf07", listOf("city_sunrise"), 5, 2),
    IosEmoji("\ud83c\udf09", listOf("bridge_at_night"), 5, 4),
    IosEmoji("\u2668\ufe0f", listOf("hotsprings"), 58, 61),
    IosEmoji("\ud83c\udfa0", listOf("carousel_horse"), 7, 31),
    IosEmoji("\ud83d\udedd", listOf("playground_slide"), 38, 50),
    IosEmoji("\ud83c\udfa1", listOf("ferris_wheel"), 7, 32),
    IosEmoji("\ud83c\udfa2", listOf("roller_coaster"), 7, 33),
    IosEmoji("\ud83d\udc88", listOf("barber"), 27, 5),
    IosEmoji("\ud83c\udfaa", listOf("circus_tent"), 7, 41),
    IosEmoji("\ud83d\ude82", listOf("steam_locomotive"), 35, 60),
    IosEmoji("\ud83d\ude83", listOf("railway_car"), 35, 61),
    IosEmoji("\ud83d\ude84", listOf("bullettrain_side"), 36, 0),
    IosEmoji("\ud83d\ude85", listOf("bullettrain_front"), 36, 1),
    IosEmoji("\ud83d\ude86", listOf("train2"), 36, 2),
    IosEmoji("\ud83d\ude87", listOf("metro"), 36, 3),
    IosEmoji("\ud83d\ude88", listOf("light_rail"), 36, 4),
    IosEmoji("\ud83d\ude89", listOf("station"), 36, 5),
    IosEmoji("\ud83d\ude8a", listOf("tram"), 36, 6),
    IosEmoji("\ud83d\ude9d", listOf("monorail"), 36, 25),
    IosEmoji("\ud83d\ude9e", listOf("mountain_railway"), 36, 26),
    IosEmoji("\ud83d\ude8b", listOf("train"), 36, 7),
    IosEmoji("\ud83d\ude8c", listOf("bus"), 36, 8),
    IosEmoji("\ud83d\ude8d", listOf("oncoming_bus"), 36, 9),
    IosEmoji("\ud83d\ude8e", listOf("trolleybus"), 36, 10),
    IosEmoji("\ud83d\ude90", listOf("minibus"), 36, 12),
    IosEmoji("\ud83d\ude91", listOf("ambulance"), 36, 13),
    IosEmoji("\ud83d\ude92", listOf("fire_engine"), 36, 14),
    IosEmoji("\ud83d\ude93", listOf("police_car"), 36, 15),
    IosEmoji("\ud83d\ude94", listOf("oncoming_police_car"), 36, 16),
    IosEmoji("\ud83d\ude95", listOf("taxi"), 36, 17),
    IosEmoji("\ud83d\ude96", listOf("oncoming_taxi"), 36, 18),
    IosEmoji("\ud83d\ude97", listOf("car", "red_car"), 36, 19),
    IosEmoji("\ud83d\ude98", listOf("oncoming_automobile"), 36, 20),
    IosEmoji("\ud83d\ude99", listOf("blue_car"), 36, 21),
    IosEmoji("\ud83d\udefb", listOf("pickup_truck"), 39, 9),
    IosEmoji("\ud83d\ude9a", listOf("truck"), 36, 22),
    IosEmoji("\ud83d\ude9b", listOf("articulated_lorry"), 36, 23),
    IosEmoji("\ud83d\ude9c", listOf("tractor"), 36, 24),
    IosEmoji("\ud83c\udfce\ufe0f", listOf("racing_car"), 10, 4),
    IosEmoji("\ud83c\udfcd\ufe0f", listOf("racing_motorcycle"), 10, 3),
    IosEmoji("\ud83d\udef5", listOf("motor_scooter"), 39, 3),
    IosEmoji("\ud83e\uddbd", listOf("manual_wheelchair"), 46, 36),
    IosEmoji("\ud83e\uddbc", listOf("motorized_wheelchair"), 46, 35),
  )
}
